### ISSUE TITLE
More maintainers needed

### ISSUE THREAD

**Issue by eirslett** [storybookjs/builder-vite#11]
This project needs more maintainers. Are you willing to contribute? Please reply on this issue, or send me a message directly.

**Comment by julrich** [comment]
Not sure if I could commit to maintaining, but definitely interested in contributing!
Not really experienced with `Vite`, but very willing to dive in ;)

**Comment by sveisvei** [comment]
I might chime in soon as well.

**Comment by 17twenty** [comment]
Happy to try and help -- I saw recent storybook post saying pluggable builders are coming but nothing official.

Our team are vite + tailwind JIT + vue3 and the WebPack/storybook misalignment causes headaches

**Comment by eirslett** [comment]
@17twenty That's great! If you run across any problems, you can open PRs here! Just send me a message if you're stuck with setting up the dev environment.

**Comment by filipw01** [comment]
I'd love to help developing this in free time. I have little experience in bundlers space so it'd be great if you could give me some tips and resources to read

**Comment by eirslett** [comment]
What you should do is join the Vite (https://chat.vitejs.dev/) and Storybook (https://storybook.js.org/community) spaces in Discord. In Vite land, there are some channels, like `#dev-server` and `#ssr` that are helpful. There is a `#vite` channel in the Storybook discord. Run a git clone of the [Vite source code](https://github.com/vitejs/vite) if you need to dig into its internals. It's also nice to clone the [Storybook source code](https://github.com/storybookjs/storybook) if you need to look at its internals, or make adjustments.

For this repo, run a git clone, npm install, and you should be good to go! You can tweak the example project (or create another example project for Vue or whatever), and they should run with the local Storybook builder.

**Comment by IanVS** [comment]
@17twenty have you been able to get storybook-builder-vite working with vue3?  Have you hit any snags?

**Comment by soulsam480** [comment]
@eirslett Don't know much about storybook, but willing to contribute by looking into issues regarding vite. Thanks

**Comment by eirslett** [comment]
@soulsam480 That's great! The most valuable contribution at this time is probably people who use Vite for their production Storybook, and finding bugs that happen in more complex scenarios. And then send bug fixes!

**Comment by schalk-b** [comment]
Are there any plans to rewrite things in typescript?

**Comment by eirslett** [comment]
> Are there any plans to rewrite things in typescript?

Not right now. We could, but (in my opinion) it's easier to use JavaScript in the backend/with Node.js because we don't need transilation or ts-node, and debugging/breakpoints is more ergonomic.

If TypeScript gives us a lot of value, we could use `// @ts-check` and JSDoc?

**Comment by JesusTheHun** [comment]
Typescript is not only about types, it's also about features that are not yet added in JS and the possibility to target specific versions of JS during transpile.
Regarding the ergonomic of running or debugging, I don't know how long has past since you last gave it a shot but things have dramatically change and debugging TS is completely transparent nowadays.

Now will those things bring value to the project, it's up to you ;)

**Comment by eirslett** [comment]
Last time I tried stepping through/debugging TypeScript code was 3 months ago. I was writing this plugin and tried to figure out what was happening internally inside Storybook (which is written in TypeScript). I ran the server code via IntelliJ, and for me it was a painful experience. Which is why this project uses JavaScript. But I'm sure we could switch to TypeScript if somebody writes a good documentation about how to set up a good/ergonomical development environment for storybook-builder-vite! I use TypeScript in my daily frontend work in the browser, I love the language, but like mentioned, I had problems with it in backend code.

**Comment by matthewhardern** [comment]
Happy to help on some of it if needed, I however don't have a major level of experience with vite. I will however try and help with some of the issues.

**Comment by Pringels** [comment]
I'm also happy to lend a hand :)

**Comment by joshwooding** [comment]
I'm happy to help :) I've had a lot of fun digging into vite and storybook.

**Comment by linkb15** [comment]
I'm happy to help 👯

**Comment by IanVS** [comment]
Thanks!  I think the best thing that people can do right now is to test out the builder in their own projects, looking for problems or rough edges.  Aside from that, we have a few issues in the tracker that could use some investigation and troubleshooting, and we'd love any help you can give there.  We're on the storybook discord in the #vite channel throughout different parts of the day, so feel free to pop in and chat there, as well!

**Comment by Jordan-Hall** [comment]
Happy to help solve any issues. We about to integrate core plugin this into [nxext ](https://nxext.dev/). So happy to help make this great

**Comment by mrauhu** [comment]
I will be glad to help to simplify the development process, more information in #188.

**Comment by szympajka** [comment]
Hey! I would like to help! :)
