### ISSUE TITLE
TypeError: (0 , import_upath.normalize) is not a function when using jest storybook addon

### ISSUE THREAD

**Issue by vudoan1708-cyber** [storybookjs/builder-vite#249]
**Describe the bug**

None of the component can be rendered due to the error which seems to be related to the addon adding jest testing framework to Storybook _(@storybook/addon-jest)_.

![image](https://user-images.githubusercontent.com/56874575/154768931-e23fd290-954e-4480-bef4-21043434b6c1.png)
![image](https://user-images.githubusercontent.com/56874575/154768956-7fe747fa-e6b5-4d65-8985-d61cb69ce545.png)

Also an irrelevant issue, which causes quite a delay in getting all the stories displayed. In the console, it logs out `[vite] connected`, however, it subsequently takes _roughly 26 seconds_ before the canvas can be completely rendered onto the screen.
![image](https://user-images.githubusercontent.com/56874575/154778002-bbcc48c6-f746-4444-b3f6-2134da9d4470.png)

**Dependencies**

```
"@storybook/addon-actions": "^6.4.13",
"@storybook/addon-docs": "^6.4.13",
"@storybook/addon-essentials": "^6.4.13",
"@storybook/addon-jest": "^6.4.13",
"@storybook/addon-links": "^6.4.13",
"@storybook/addon-svelte-csf": "^1.1.0",
"@storybook/addons": "^6.4.13",
"@storybook/svelte": "^6.4.13",
"@storybook/theming": "^6.3.6",
"@sveltejs/vite-plugin-svelte": "^1.0.0-next.36",
"@testing-library/jest-dom": "^5.12.0",
"@testing-library/svelte": "^3.0.3",
"@testing-library/user-event": "^13.1.9",
"fetch-mock": "^9.11.0",
"jest": "^26.6.3",
"storybook-addon-themes": "^6.1.0",
"storybook-builder-vite": "^0.1.16",
```
**And a simple configuration in main.cjs**

```
module.exports = {
  core: {
    builder: "storybook-builder-vite"
  },
  stories: [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx|svelte)"
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-svelte-csf",
    "storybook-addon-themes",
    "@storybook/addon-jest"
  ],
  framework: "@storybook/svelte",
  svelteOptions: {
    preprocess: require("svelte-preprocess")()
  },
}
```

Any help would be very appreciated.
Thanks.

**Comment by IanVS** [comment]
I'm not super-surprised that a jest addon is not well-behaved.  Jest always seems to assume that it's running in node, and since vite does not polyfill node builtins, jest kind of falls on its face, unfortunately.  

>Also an irrelevant issue, which causes quite a delay in getting all the stories displayed. In the console, it logs out [vite] connected, however, it subsequently takes roughly 26 seconds before the canvas can be completely rendered onto the screen.

This is a bit of a downside of vite.  It sends all of the modules separately in development, so that it doesn't have to spend time bundling and a single module can be HMRed during dev.  The production build should be much faster to start up.

If you're willing to experiment a bit, you can enable `storyStoreV7`, which causes only the modules needed for each story to be downloaded, and dynamically imports others as you change stories.  It can have a big impact on initial load time.

**Comment by vudoan1708-cyber** [comment]
> @vudoan1708-cyber I was able to fix this by polyfilling `'path`` following this article: https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2
> 
> My Vite config (which I merge into Storybook config):
> 
> ```
> /*
> 	Node Polyfills Config
> 	---------------------
> 	`path` needs to be polyfilled for Jest which is required to allow
> 	@storybook/addon-jest to work with Vite.
> 	Polyfill source: https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2
> */
> const polyfillsConfig: UserConfig = {
> 	resolve: {
> 		alias: {
> 			path: 'rollup-plugin-node-polyfills/polyfills/path',
> 		},
> 	},
> 	optimizeDeps: {
> 		esbuildOptions: {
> 			plugins: [
> 				// @ts-expect-error Seems the typings are incorrect?
> 				NodeModulesPolyfillPlugin(),
> 			],
> 		},
> 	},
> 	build: {
> 		rollupOptions: {
> 			plugins: [
> 				// Enable rollup polyfills plugin
> 				// used during production bundling
> 				// @ts-expect-error Seems the typings are incorrect?
> 				rollupNodePolyFill(),
> 			],
> 		},
> 	},
> };
> ```

Thank so much for your suggestions!

That didn't work for me when polyfilling Jest in the `vite.config.js` file, however, it does, when the polyfill is in the `main.cjs` file.
Here is how I did it

`async viteFinal(config, { configType }) {
    if (configType === 'DEVELOPMENT') {
      /*
        Node Polyfills Config
        ---------------------
        `path` needs to be polyfilled for Jest which is required to allow
        @storybook/addon-jest to work with Vite.
        Polyfill source: https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2
      */
      config.resolve = {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
          path: 'rollup-plugin-node-polyfills/polyfills/path',
        }
      };

      config.optimizeDeps = {
        ...config.optimizeDeps,
        // customize the Vite config here
        include: [
          '@storybook/svelte',
          '@storybook/addon-svelte-csf',
          '@storybook/addon-jest',
          'fetch-mock',
          'chart.js',
          ...config.optimizeDeps.include,
        ],
        esbuildOptions: {
          plugins: [
            NodeModulesPolyfillPlugin(),
          ],
        }
      };

      config.build = {
        ...config.build,
        rollupOptions: {
          plugins: [
            // Enable rollup polyfills plugin
            // used during production bundling
            rollupNodePolyFill(),
          ],
        },
      }
    }

    // return the customized config
    return config;
  },
};`

I'm pretty happy with this, however, another issue came up: Every other generic component that doesn't have a decorator function injected to a Story works perfectly fine, other components that require decorator functions to mock API response, return various types of error.
So I assume this next issue could be due to the decorator functions not working properly. Not sure if we already have a fix for this, but any help will be very much appreciated.

Thanks.

**Comment by IanVS** [comment]
@vudoan1708-cyber if you're able to create a reproduction of the issue you're having, it will be a lot easier to help troubleshoot.

**Comment by vudoan1708-cyber** [comment]
@IanVS I just created another bug issue [here](https://github.com/storybookjs/builder-vite/issues/352), in regards to the issue raised here, I think it has been resolved, and can be closed now.

Thanks a lot for you guy's helps.
