### ISSUE TITLE
[Bug] Insert Storybook's iframe.css before vendor.css

### ISSUE THREAD

**Issue by NexZhu** [storybookjs/builder-vite#300]
### Describe the bug

Currently Storybook's `iframe.css` is inserted after the `vendor.css` bundled by Vite, resulting in `iframe.css` overriding `vendor.css`. In my case, vendor.css includes styles from the UI library, and the button `backround-color` is override by `background-color: transparent` from `iframe.css`.

### Expected behavior

`iframe.css` should be inserted in front of all other stylesheets.

### Screenshots and/or logs

![image](https://user-images.githubusercontent.com/4370605/161253994-37beeb27-c19e-467c-be27-037764b2aa34.png)

**Comment by IanVS** [comment]
@NexZhu would you like to submit a PR to fix this?

**Comment by IanVS** [comment]
Actually, are you able to share a minimal reproduction of the issue?  I'd like to be certain that this change should happen.

**Comment by NexZhu** [comment]
Repoduction repo:

https://github.com/lingTing8/style-issue-reproduction

```bash
npm run build-storybook
npx http-server storybook-static
```

**Comment by NexZhu** [comment]
> Are you able to share a minimal reproduction of the issue? I'd like to be certain that this change should happen. I think iframe.css is your own styles, not anything that storybook is adding...

There's no `iframe.css` in our codebase.

**Comment by NexZhu** [comment]
Found `iframe.css` is injected by `vite-plugin-inspect`, closing the issue.
