### ISSUE TITLE
[Bug] Storybook-6.5.0-alpha.53 breaks this builder

### ISSUE THREAD

**Issue by rickdunkin** [storybookjs/builder-vite#304]
### Describe the bug

[This PR merged in 6.5.0-alpha.53](https://github.com/storybookjs/storybook/pull/17282) breaks this builder as it moved `composeConfigs` ([used here](https://github.com/storybookjs/builder-vite/blob/main/packages/builder-vite/codegen-modern-iframe-script.ts#L24)) from `@storybook/preview-web` to `@storybook/store`

### Steps to reproduce the behavior

1. Upgrade Storybook to `6.5.0-alpha.53` or higher
2. Stories no longer render due to `composeConfigs` no longer being in `@storybook/preview-web`

![image](https://user-images.githubusercontent.com/3039127/161401419-1f3fe5c7-b981-49e3-9504-77a401c6b4e7.png)

**Comment by IanVS** [comment]
@rickdunkin thanks for the report!  Could you try out the latest storybook alpha (55) and confirm that this is fixed for you?

**Comment by rickdunkin** [comment]
@IanVS I'm no longer getting that `composeConfigs` error, thanks! There is a new error I'm now related to the preview and `@storybook/addon-jest` coming from `node_modules/.vite-storybook/deps/@storybook_addon-jest.js`, but if I have time to dig into it I'll just open another issue

**Comment by IanVS** [comment]
Could it be the same as https://github.com/storybookjs/builder-vite/issues/249?

**Comment by rickdunkin** [comment]
I don't believe it's the same issue as I actually don't have addon-jest included in my config (though I do have it installed as I would like to eventually use it). The preview is returning a 503 from the vite-storybook's addon-jest file (which I don't totally get why that's there or being used if it's not included in my config?)

**Comment by IanVS** [comment]
Yeah, sounds like a new issue, ideally with a reproduction, would be great. Thanks.
