### ISSUE TITLE
[Bug] Importing "virtual:pwa-register" could not be resolved

### ISSUE THREAD

**Issue by Hydrair** [storybookjs/builder-vite#311]
### Describe the bug

I'm building a PWA with Storybook and builder-vite. For convenience i wanted to add  [Vite-Plugin-PWA](https://vite-plugin-pwa.netlify.app/). To inform the user about an update a ReloadPrompt was added, which is also mentioned in the docs. The ReloadPrompt Component uses an import `import { useRegisterSW } from "virtual:pwa-register/react";` but the builder does not seem to find the dependency.

### Steps to reproduce the behavior

1. Add Vite-Plugin-PWA to package.json
2. Create the ReloadPrompt.tsx from [here](https://vite-plugin-pwa.netlify.app/frameworks/react.html#prompt-for-update)
3. `yarn start-storybook`

### Expected behavior

Builder-vite should successfully import the virtual module

### Screenshots and/or logs

```
The following dependencies are imported but could not be resolved:
virtual:pwa-register/react (imported by C:/Projekte/PWA/src/components/ReloadPrompt/ReloadPrompt.tsx)
```

### Environment

 - OS: [e.g. iOS] Windows
 - Node.js version: [e.g. v12.17.0] v14.18.0
 - Yarn version: [e.g. 6.14.4] 1.22.17
 - Browser (if applicable): [e.g. chrome, safari] Brave 
 - Browser version (if applicable): [e.g. 22] 1.37.109

### Additional context

When adding VitePluginPWA to the Vite config in Storybooks main.js the error is not shown, but Storybook wont build the iframe properly.

main.js:
```
const { VitePWA } = require("vite-plugin-pwa");

module.exports = {
    core: {
        builder: "@storybook/builder-vite",
    },
    stories: ["../src/**/**/*.stories.tsx"],
    addons: ["@storybook/addon-essentials"],
    // staticDirs: ['../public'],
    framework: "@storybook/react",

    async viteFinal(config, { configType }) {
        config.optimizeDeps.include = [
            "react-router-dom",
            "http-proxy-middleware",
            "vite",
            "vite-plugin-pwa",
            "fast-deep-equal",
            ...config.optimizeDeps.include,
        ];
        config.plugins.push(VitePWA({}));
        return config;
    },
};

```

**Comment by GuyGooL5** [comment]
this `main.js` snippet is the full thing? If so I guess you're missing the import of VitePWA

try importing it using ``import { VitePWA } from 'vite-plugin-pwa';`` or ``const {VitePWA} = require('vite-plugin-pwa');`` depending on your module resolution.

**Comment by Hydrair** [comment]
Oh, my bad, i did import it and updated the post.

The command line throws no more error but the console in the browser does:
```
Uncaught SyntaxError: The requested module '/node_modules/fast-deep-equal/index.js?v=9da7d76d' does not provide an export named 'default' (at args.js?v=9da7d76d:54:8)
```

**Comment by IanVS** [comment]
That's strange, `fast-deep-equal` is included in our `optimizeDeps.include`.  Are you able to create a reproduction repo that we can look into?

**Comment by Hydrair** [comment]
Yes, here it is: https://github.com/Hydrair/MWE-import-virtual
Using `yarn` and `yarn storybook` it produces the same behavior like the original project. After optimizing dependencies.

**Comment by Hydrair** [comment]
> ```
> ✘ [ERROR] No matching export in "browser-external:path" for import "extname"
> 
>     node_modules/@rollup/pluginutils/dist/es/index.js:1:9:
>       1 │ import { extname, sep, resolve, posix } from 'path';
> ```
Okay this was fixed by adding `path` and `fs` to `config.optimizeDeps.exclude`, inspired by https://github.com/sveltejs/kit/issues/1570#issuecomment-856808078. 

But now i'm at the original error again and `virtual:pwa-register/react` can not be solved.

**Comment by Hydrair** [comment]
Alright fixed it with https://github.com/windicss/windicss/issues/267#issuecomment-947881136.

The `main.js` now looks like this:
```
const VitePWA = require("vite-plugin-pwa").VitePWA;
const { dirname } = require("path");

module.exports = {
    core: {
        builder: "@storybook/builder-vite",
    },
    stories: ["../src/**/**/*.stories.tsx"],
    addons: ["@storybook/addon-essentials"],
    framework: "@storybook/react",
    async viteFinal(config, { configType }) {
        config.optimizeDeps.include = [
            "react-router-dom",
            "vite",
            "vite-plugin-pwa",
            ...config.optimizeDeps.include,
        ];
        config.optimizeDeps.exclude = ["path", "fs"];
        config.plugins = config.plugins ?? [];
        config.plugins.push(
            VitePWA({
                root: dirname(__dirname),
            })
        );
        return config;
    },
};
```

Apparently by specifying the `root` Vite knows how to look for the exports.

Thanks for your help!
