### ISSUE TITLE
[Bug] Not working with chromatic version >= 0.1.23

### ISSUE THREAD

**Issue by fazulk** [storybookjs/builder-vite#319]
### Describe the bug

`0.1.23` and `0.1.24` dont render stories inside chromatic.

### Steps to reproduce the behavior

1. Install `@storybook/builder-vite": "0.1.23"`
2. Deploy to chromatic

### Expected behavior

The most basic component without any dependencies should pass tests and render. 

### Screenshots and/or logs

Each component errors out and is unable to render.
![image](https://user-images.githubusercontent.com/21964900/162087599-a9ca7811-b962-4f72-9b78-8db9b1d848ea.png)
This is a basic vue3 component, that only displays text.

### Environment

 - OS: Mac
 - Node.js version: 14.18.1
 - NPM version: [e.g. 6.14.4]
 - Browser (if applicable): chrome

### Additional context

Version 0.1.22 is working fine. Although it looks like there is a race condition with msw, but that is a separate ticket. 

Building storybook locally works fine with no issues.

**Comment by IanVS** [comment]
Hmmm, this seems strange.  Could you try running `yarn build-storybook` (or whatever command you use to build your production storybook), and then `npx http-server storybook-static` to view the built stories?   I'm wondering if there's maybe an error there, and perhaps there might be more details in the console.

**Comment by fazulk** [comment]
Got it working by updating vite from `2.8.6` to `2.9.1`, thanks!
