### ISSUE TITLE
[Bug] Dynamic require of "@storybook/addons" is not supported

### ISSUE THREAD

**Issue by IanVS** [storybookjs/builder-vite#327]
### Describe the bug

I tried updating my app to 0.1.26, and I'm now getting an error:

```
index.js?v=dbebbc0a:56 Error reading preview.js:
Dynamic require of "@storybook/addons" is not supported
```

It occurs no matter whether I'm using `storyStoreV7`.

### Steps to reproduce the behavior

I'll try to make a reproduction soon.  I'm curious if anyone else is seeing this though.

I tried removing my `package-lock.json` and re-installing, to be sure I didn't have some kind of transitive dependency mismatch, but the error persists.

Edit: this seems related to https://github.com/hipstersmoothie/storybook-dark-mode.  When I remove that addon, storybook builds fine.

**Comment by IanVS** [comment]
I think this is because the built version (cjs) of the storybook-dark-mode plugin has `var addons_1 = require("@storybook/addons");`, which vite pre-bundles into ` var addons_1 = __require("@storybook/addons");`, where `__require` checks to see if `require` is defined and if so, uses it.  The shim comes from esbuild, and is explained here: https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#01229

That's as far as I'm getting for now, I'll try to figure out what needs to be done next.  And hopefully this isn't a broad issue with more addons, either.

**Comment by benbender** [comment]
@IanVS just wanted to say "thank you" for all your efforts! appreciated!

**Comment by IanVS** [comment]
@benbender, thanks!  Are you seeing this error as well?

**Comment by benbender** [comment]
@IanVS Yes, I saw it once, but can't reproduce it. It occurred while I was playing with your "debundling-pr" which seems logical now after I saw the revert message...
