### ISSUE TITLE
[Bug] StorybookConfig type does not recognize `viteFinal` as a property

### ISSUE THREAD

**Issue by bilalq** [storybookjs/builder-vite#329]
### Describe the bug

I've written my Storybook config in TypeScript as a `main.ts` file instead of a `main.js` file, but the typings of `StorybookConfig` do not recognize `viteFinal` as a valid property.

```
[tsserver 2322] [E] Type '{ stories: string[]; staticDirs: string[]; addons: string[]; framework: string; core: { builder: string; }; features: { storyStoreV7: true; }; viteFinal(storybookDefaultConfig: Record<string, any>, { configType: _configType }: { ...; }): Promise<...>; }' is not assignable to type 'StorybookConfig'.
  Object literal may only specify known properties, and 'viteFinal' does not exist in type 'StorybookConfig'.
```

The definition for those types actually live in [@storybook/core-common](https://github.com/storybookjs/storybook/blob/next/lib/core-common/src/types.ts#L311). I wasn't sure whether to create this issue in the main repo or here, but figured this was more applicable.

### Steps to reproduce the behavior

1. Create a clean vite project
2. Initialize latest storybook setup with `npx sb@next init --builder @storybook/builder-vite`
3. Rename `main.js` to `main.ts` and try to assign the config object to the type of `StorybookConfig`. 
4. See type error.

Here is my example config in `main.ts`:

```typescript
import type { StorybookConfig } from '@storybook/core-common'
import { mergeConfig } from 'vite'
import appViteConfig from '../vite.config'

const config: StorybookConfig = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  staticDirs: ['../public'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  framework: '@storybook/react',
  core: {
    builder: '@storybook/builder-vite',
  },
  features: {
    storyStoreV7: true,
  },
  async viteFinal(
    storybookDefaultConfig: Record<string, any>,
    { configType: _configType }
  ) {
    // We combine Storybook's default Vite config with our own. Any Storybook
    // specific extensions are customized here as well.
    return mergeConfig(mergeConfig(storybookDefaultConfig, appViteConfig), {
      optimizeDeps: {
        // Including things here works around Vite/storybook prebundling issues
        // https://github.com/storybookjs/builder-vite/blob/70a9079fc2d545c046d63ff47666afdf8bb2810e/packages/builder-vite/README.md#known-issues
        include: ['msw-storybook-addon'],
      },
    })
  },
}

module.exports = config
```

### Expected behavior

The `viteFinal` property should be a recognized property in the typings.

### Screenshots and/or logs

N/A

### Environment

 - OS: MacOS 12.0.1
 - Node.js version: 16.14.2
 - NPM version: 8.5.0
 - Browser (if applicable): N/A
 - Browser version (if applicable): N/A
 - Device (if applicable): MacBook Pro (14-inch, 2021)

### Additional context

N/A

**Comment by IanVS** [comment]
Thanks for opening this issue, @bilalq. I agree this would be a great change to make.  Would you be willing to submit a PR to https://github.com/storybookjs/storybook?  The team has committed to better first-class support of the vite builder, so I think that adding the type there would not be unwelcome.

**Comment by ahnpnl** [comment]
+1 for this too, I just tried out `main.ts` and I ran into this

**Comment by bilalq** [comment]
I'm happy to make the PR, but I don't fully understand what the shapes should be. I'm assuming the first argument and the return type should be the type of `UserConfig` from Vite. What about the second argument though? What forms can its shape potentially take?

**Comment by IanVS** [comment]
Awesome, thanks @bilalq!  

The first argument should be `InlineConfig` from Vite.

The second argument is `Options`, from https://github.com/storybookjs/storybook/blob/d086bbcfac38fd637670d1383accf4b1f184d9d3/lib/core-common/src/types.ts?rgh-link-date=2022-04-10T06%3A21%3A18Z#L214.

**Comment by bilalq** [comment]
I thought about this a bit more:

Does it make sense to just expose a different interface in `@storybook/builder-vite` that extends `StorybookConfig` from `@storybook/core-common`?

This way, the builder is free to update the shape as needed and the core package doesn't need to take deps on Vite for typings.

**Comment by IanVS** [comment]
That sounds good in theory, how do you propose to accomplish it?

**Comment by dohooo** [comment]
@IanVS #349 Hi~

**Comment by IanVS** [comment]
This has been released in https://github.com/storybookjs/builder-vite/releases/tag/v0.1.31, thanks for the contribution, @dohooo!
