### ISSUE TITLE
[Bug] Storybook Build Fails To Inject Build Files in Index after Updating to Vite 2.9

### ISSUE THREAD

**Issue by stephenhebert** [storybookjs/builder-vite#336]
### Describe the bug

`build-storybook` seems to run normally, produces all expected files and no build errors are displayed, but built files are not injected into index.html, which is output as:
```
<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="<%= BASE_URL %>favicon.ico">
    <title><%= htmlWebpackPlugin.options.title %></title>
  </head>
  <body>
    <noscript>
      <strong>We're sorry but <%= htmlWebpackPlugin.options.title %> doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  </body>
</html>

``` 

### Steps to reproduce the behavior

Update vite to v2.9

### Expected behavior

For storybook to build properly

### Environment

 - OS: MacOS Big Sur v11.6
 - Node.js version: v14.17.3
 - NPM version: v6.14.13

### Additional context

`start-storybook` works as expected with vite v2.9.1
`build-storybook` works fine if vite is downgraded to previous version of v2.8.6

Other package versions:
```
    "@storybook/builder-vite": "^0.1.28",
    "@storybook/vue3": "^6.5.0-alpha.47",
    "vue": "^3.2.31",
    "@babel/core": "^7.17.5",
```

It seems that there is an issue related to or prior to webpack injecting files, after files (modules, assets, etc) have been output.

**Comment by IanVS** [comment]
@stephenhebert do you maybe have a leftover `index.html` file in your `/public` directory, or something?  I see mention of `htmlWebpackPlugin`, which is what makes me think you might.

**Comment by stephenhebert** [comment]
@IanVS There is an index.html in my public directory.  Are you suggesting that it should it not be there, or that should it be a different index.html?

Storybook does seem to be using webpack to bundle, though it is configured to build with vite.  I assume that is also expected.

**Comment by IanVS** [comment]
Correct, you should not have an `index.html` in your public directory.  Vite does not process those files, it simply moves them straight over into your build folder.  https://vitejs.dev/guide/#index-html-and-project-root

And yes, webpack will still be used to create the "manager" of storybook (the UI that it provides).  That's nothing to be alarmed about.  :)

**Comment by stephenhebert** [comment]
Removing `public/index.html` resolved the issue!  Such a simple resolution!  @IanVS Thank you for your help and your very quick response!
