### ISSUE TITLE
[Bug] Cannot upgrade to React 18

### ISSUE THREAD

**Issue by tanettrimas** [storybookjs/builder-vite#342]
### Describe the bug

Cannot upgrade to React@18.0.0 because there is a peerDependency to `@storybook/core-common@6.4.22`. If this was upgraded to version `6.5.0-alpha.64` this would fix support for React 18 peerDependency

### Steps to reproduce the behavior

1. Apply react 18 as dependency
2. Watch the `npm install` fail

### Expected behavior

Storybook to work successfully with React 18 and Vite

### Screenshots and/or logs

<img width="703" alt="Skjermbilde 2022-04-19 kl  09 02 53" src="https://user-images.githubusercontent.com/42898343/163946492-e35eb3df-a71c-431e-8465-62e974e72d2b.png">

<img width="372" alt="Skjermbilde 2022-04-19 kl  09 13 17" src="https://user-images.githubusercontent.com/42898343/163946587-688badd1-957d-4f49-b520-ed276e4c7dfc.png">

### Environment

 - OS: Mac OS Catalina v12.3.1
 - Node.js version: 16.3.1
 - NPM version: 8.1.2

**Comment by IanVS** [comment]
Alpha versions do not work well with peer deps and npm.  I suggest using `npm install --legacy-peer-deps`

**Comment by tanettrimas** [comment]
I tried that now, but now it seems that it tries to run webpack instead of vite when I try to build it: 

Here is my setup
![Skjermbilde 2022-04-19 kl  16 18 23](https://user-images.githubusercontent.com/42898343/164025191-79ed15b0-0d38-4743-a9c2-8125a875a081.png)
![Skjermbilde 2022-04-19 kl  16 17 54](https://user-images.githubusercontent.com/42898343/164025193-32aad079-5763-4f41-8c4c-e12f22d2de9a.png)

**Comment by tanettrimas** [comment]
Not sure if related, but I also get this error without `@mdx-js/react`
![Skjermbilde 2022-04-19 kl  16 25 02](https://user-images.githubusercontent.com/42898343/164026763-935be60c-21f8-4fed-835b-4c32d751f7b5.png)

**Comment by tanettrimas** [comment]
But yes, I downgraded and went away from the alpha version as suggested - then it worked.

**Comment by IanVS** [comment]
It sounds like maybe some old transitive deps might have been causing problems.  You could try removing your lockfile and reinstalling.  And webpack is still used to build the manager, even with the vite builder for the preview.  If you want to wait for 6.5 to go stable before updating, it shouldn't be long.
