### ISSUE TITLE
[Bug] New styles from #339 cause issues for components added to body

### ISSUE THREAD

**Issue by ChrisW-B** [storybookjs/builder-vite#343]
### Describe the bug

The style rule added to prevent FOUC hides all direct children of the body, which means elements appended to the body no longer display. This means things such as the radix-ui drawer component are no longer visible in Storybook.

This seems to be a result of

```css
    body > * {
      display: none !important;
    }
```

### Steps to reproduce the behavior

1. Create an element which uses a root element on body that doesn't have id `#root`
2. Attempt to view in Storybook.
3. It will have the property `display: none !important` on its root element

### Expected behavior

Element should be visible.

### Screenshots and/or logs

![Screen Shot 2022-04-19 at 10 23 08 AM](https://user-images.githubusercontent.com/2490974/164026231-2d961db8-0157-42b7-975f-7cbd4b885d05.png)

### Environment

 - OS: MacOS
 - Node.js version: v16.14.2
 - NPM version: 8.7.0
 - Browser (if applicable): chrome, firefox
 - Browser version (if applicable): 103.0.5010.0, 101.0a1 (2022-04-18)

**Comment by IanVS** [comment]
@ChrisW-B I believe I have a solution, in https://github.com/storybookjs/builder-vite/pull/346.  If you'd like to test it out, you can make the same change from the PR in the `dist` folder of your `node_modules/@storybook/builder-vite`.  But, I think it's a much better approach than what we currently have.

**Comment by samydoesit** [comment]
We do have the same problem, i tried the suggested fix from #346 and it works in our case.

**Comment by ChrisW-B** [comment]
@IanVS perfect, thank you!
