### ISSUE TITLE
[Bug] Storybook addons don't work after migrating to vite

### ISSUE THREAD

**Issue by renardelyon** [storybookjs/builder-vite#348]
### Describe the bug

I've been trying migrating storybook to vite, but when it start, storybook addons don't seem to work

<img width="1031" alt="Screen Shot 2022-04-22 at 16 05 10" src="https://user-images.githubusercontent.com/79710053/164674753-4ebb52ec-c2f6-4383-ba37-a7d5b770a4ab.png">

### Steps to reproduce the behavior

Here is my example config in `main.js`:
```javascript
var path = require('path');
const { mergeConfig } = require('vite')

module.exports = {
  stories: ['../src/**/*.stories.@(js|jsx|ts|tsx|mdx)'],
  addons: [
    '@storybook/addon-docs',
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-storysource',
    '@storybook/addon-a11y',
    '@storybook/addon-controls',
    'storybook-addon-jsx'
  ],
  framework: "@storybook/react",
  core: {
    builder: '@storybook/builder-vite'
  },
  async viteFinal(config) {
    return mergeConfig(config, {
      optimizeDeps: {
        include: [
          '@storybook/addon-docs/blocks',
          '@storybook/addon-docs/dist/esm/frameworks/common/config.js',
          '@storybook/addon-docs/dist/esm/frameworks/react/config.js',
          '@storybook/react/dist/esm/client/preview/config',
          '@storybook/addon-links/dist/esm/preset/addDecorator.js',
          '@storybook/addon-actions/dist/esm/preset/addDecorator.js',
          '@storybook/addon-actions/dist/esm/preset/addArgs.js',
          '@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js',
          '@storybook/addon-backgrounds/dist/esm/preset/addParameter.js',
          '@storybook/addon-measure/dist/esm/preset/addDecorator.js',
          '@storybook/addon-outline/dist/esm/preset/addDecorator.js',
          '@storybook/addon-a11y/dist/esm/a11yRunner.js',
          '@storybook/addon-a11y/dist/esm/a11yHighlight.js',
          'antd',
          'styled-components',
          'clsx',
          "@fortawesome/fontawesome-free",
          'html-react-parser',
          'react-text-mask',
          '@ant-design/icons',
          'text-mask-addons/dist/createNumberMask',
          'react-otp-input',
          'date-fns',
          'moment',
          'rxjs',
          'rxjs/operators',
          'antd/lib/table',
          'virtualizedtableforantd4',
          'draft-js',
          'react-toastify',
          'draft-convert',
          'antd/lib/switch',
          'moment/locale/id',
          'moment/locale/en-gb',
          'rc-picker/lib/generate/dateFns',
          'antd/lib/date-picker/generatePicker',
          'date-fns/locale',
        ],
        exclude: []
      }
    })
  }
};
```

### Expected behavior

<img width="1031" alt="Screen Shot 2022-04-22 at 16 08 06" src="https://user-images.githubusercontent.com/79710053/164680492-ec0df03e-1993-4a69-a77a-669a6d64c4a4.png">

### Screenshots and/or logs

N/A

### Environment

- OS: macOS Monterey v12.3
 - Node.js version: v14.17.0
 - NPM version: 6.14.4

### Additional context

N/A

**Comment by IanVS** [comment]
Hi, what version of vite are you using?  And can you share the output of `npx sb@next info`?  With newer versions of vite, you should not need to specify all of those optimizeDeps.include.  are there any errors in your browser console?

**Comment by renardelyon** [comment]
Vite version that I used is 2.7.13, the output of `npx sb@next` info is:

**Comment by renardelyon** [comment]
Vite version that I used is 2.7.13, the output of `npx sb@next` info is: 
```
Environment Info:

  System:
    OS: macOS 12.3
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Safari: 15.4
  npmPackages:
    @storybook/addon-a11y: 6.4.22 => 6.4.22 
    @storybook/addon-actions: 6.4.22 => 6.4.22 
    @storybook/addon-controls: 6.4.22 => 6.4.22 
    @storybook/addon-docs: 6.4.22 => 6.4.22 
    @storybook/addon-essentials: 6.4.22 => 6.4.22 
    @storybook/addon-links: 6.4.22 => 6.4.22 
    @storybook/addon-storysource: 6.4.22 => 6.4.22 
    @storybook/addons: 6.4.22 => 6.4.22 
    @storybook/builder-vite: ^0.1.29 => 0.1.29 
    @storybook/react: 6.4.22 => 6.4.22 
```

I've tried upgrading vite version to 2.9.5 and removing optimizeDeps.include, but storybook addons still didn't work. I'm using javascript and the browser doesn't emit any console error.

**Comment by IanVS** [comment]
Can you share a minimal reproducable repository?  I'm not sure how else I can help troubleshoot this unless I can poke around in it a little bit.

**Comment by renardelyon** [comment]
> One other thing you can try, is to set the `reactDocgen` option manually:
> 
> ```
> // main.js
> 
> module.exports = {
> 	typescript: {
> 		reactDocgen: 'react-docgen',
> 	},
> 	...
> }
> ```

I tried it and it worked. I think this issue has been resolved. Thanks, @IanVS  for your help.

**Comment by IanVS** [comment]
Do you have `typescript` anywhere in your package.json?  that's what we use to try to determine whether we should use typescript or react-docgen.

**Comment by renardelyon** [comment]
Yes, I have typescript in my package.json

**Comment by IanVS** [comment]
@joshwooding I wonder if we should always default to `react-docgen`, and maybe give some kind of suggestion in the terminal output to use `react-docgen-typescript` if we detect typescript.  The failure mode exposed here when we guess incorrectly is pretty disastrous.
