### ISSUE TITLE
[Bug] Using fetch-mock with the decorator function results in internal error in storybook-builder-vite

### ISSUE THREAD

**Issue by vudoan1708-cyber** [storybookjs/builder-vite#352]
### What version of `vite` are you using?

2.7.13

### System info and storybook versions

**System:**

- OS: Windows 10

- CPU: AMD Ryzen 7 5700U with Radeon Graphics

**Binaries:**

- Node: v14.18.0

- npm: 6.14.15

**npmPackages:**
```
"devDependencies": {
    "@babel/core": "^7.16.7",
    "@esbuild-plugins/node-modules-polyfill": "^0.1.4",
    "@ota-meshi/eslint-plugin-svelte": "^0.24.0",
    "@storybook/addon-actions": "^6.4.13",
    "@storybook/addon-docs": "^6.4.13",
    "@storybook/addon-essentials": "^6.4.13",
    "@storybook/addon-jest": "^6.4.13",
    "@storybook/addon-links": "^6.4.13",
    "@storybook/addon-svelte-csf": "^1.1.0",
    "@storybook/builder-vite": "^0.1.30",
    "@storybook/svelte": "^6.4.13",
    "@sveltejs/vite-plugin-svelte": "^1.0.0-next.36",
    "babel-loader": "^8.2.3",
    "eslint": "^8.6.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-storybook": "^0.5.5",
    "fetch-mock": "^9.11.0",
    "jest": "^27.5.1",
    "jest-canvas-mock": "^2.3.1",
    "jest-fetch-mock": "^3.0.3",
    "postcss-html": "^1.3.0",
    "stylelint": "^14.2.0",
    "stylelint-config-html": "^1.0.0",
    "stylelint-config-standard": "^24.0.0",
    "stylelint-order": "^5.0.0",
    "svelte": "^3.46.2",
    "svelte-loader": "^3.1.2",
    "svelte-preprocess": "^4.10.1",
    "vite": "^2.7.13"
  },
  "dependencies": {
    "body-scroll-lock": "^4.0.0-beta.0",
    "chart.js": "^3.7.1",
    "moment": "^2.29.3",
    "tippy.js": "^6.3.7"
  }
```

### Describe the Bug

Every other generic component that doesn't have a decorator function injected to a Story works perfectly fine, other components that require decorator functions to mock API response, return various types of error.
So I assume this issue could be due to either the [[fetch-mock library](https://www.wheresrhys.co.uk/fetch-mock/)] doesn't work properly with storybook running on vite, or the storybook's decorator function does not work correctly with the current version of this library.
_Please have a look at error reproduction in the Button component's story: **Make API Call using Fetch-mock**._

Any help will be very much appreciated.

Thanks.

### Link to Minimal Reproducible Example

https://github.com/vudoan1708-cyber/storybook-builder-vite-error-reproduce

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Thanks for the reproduction, @vudoan1708-cyber.  I traced it down to an issue with a sub-dependency of fetch-mock, TR46.  I believe it's the same issue as, or at least related to, https://github.com/jsdom/tr46/issues/28.  

In the bundled code of fetch-mock's `server.js` file, we see:

```js
var mappingTable = /*#__PURE__*/Object.freeze({
	__proto__: null
});

var mappingTable$1 = getCjsExportFromNamespace(mappingTable);

...

function findStatus(val, { useSTD3ASCIIRules }) {
  let start = 0;
  let end = mappingTable$1.length - 1;

  while (start <= end) {
   ...
  }

  return null;
}

...const [status, mapping] = findStatus(ch.codePointAt(0), { useSTD3ASCIIRules });
```

So, we see here that `mappingTable`, is empty, so `findStatus` returns `null`, which breaks the last line above.  This might be an error within the bundler config of `fetch-mock`, or a problem with the `mappingTable.json` that tr46 is generating, or maybe something else.  But, it seems it's not an error within the storybook vite builder itself.  I hope you're able to resolve it, or find an alternative to fetch-mock that works for your use case (I might suggest msw or mirage).
