### ISSUE TITLE
[Bug] After clicking "show code" first time Object Object is shown

### ISSUE THREAD

**Issue by MarkiyanPyts** [storybookjs/builder-vite#355]
### What version of `vite` are you using?

^2.9.5

### System info and storybook versions

System macOS Monterey 12.2.1

Browsers:
Chrome Version 100.0.4896.127 (Official Build) (arm64)

### Describe the Bug

After running build-storybook and serving it in the production "show code" the button displays "Object object" instead of code.

![image](https://user-images.githubusercontent.com/6214703/165531656-ca95a70f-20df-48ab-8158-d40b80673974.png)

I created a project using 
`npm create vite@latest`

Then installed story book there 
`npx sb init --builder @storybook/builder-vite`

No additional changes were needed to reproduce this.

Note: this will work properly during `npm run storybook` breaks only for prod 

### Link to Minimal Reproducible Example

https://github.com/MarkiyanPyts/story-book-vite-object-object-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Thanks for the report and for the reproduction, this is a strange one indeed.  I updated to the 6.5.0 beta, and the issue persisted.  Then I tried with the webpack builder, and the issue also persisted.  So, I think this is a problem with storybook itself, though I'm not sure exactly what part of it.  Would you mind opening an issue in the main https://github.com/storybookjs/storybook repo?  I think it's more likely you'll be able to get help there.  

Thanks again!
