### ISSUE TITLE
[Bug] storyStoreV7 is not compatible with framework: "@storybook/web-components"

### ISSUE THREAD

**Issue by boeto** [storybookjs/builder-vite#370]
### What version of `vite` are you using?

2.9.7

### System info and storybook versions

Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 100.0
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^6.4.22 => 6.4.22 
    @storybook/addon-essentials: ^6.4.22 => 6.4.22 
    @storybook/addon-links: ^6.4.22 => 6.4.22 
    @storybook/builder-vite: ^0.1.33 => 0.1.33 
    @storybook/web-components: ^6.4.22 => 6.4.22 

##  when not set storyStoreV7:

update /src/my-element.ts ,  got the Log : `[vite] page reload src/my-element.ts `

The expected result should be: `[vite] hmr update /src/my-element.ts`

## when set `storyStoreV7: true`,

update /src/my-element.ts, then got the error Log:

``` bash
Failed to execute 'define' on 'CustomElementRegistry': the name "my-element" has already been used with this registry
Error: Failed to execute 'define' on 'CustomElementRegistry': the name "my-element" has already been used with this registry
    at legacyCustomElement (http://localhost:6008/node_modules/.vite-storybook/deps/lit_decorators_js.js?v=53feff7d:16:25)
    at http://localhost:6008/node_modules/.vite-storybook/deps/lit_decorators_js.js?v=53feff7d:29:99
    at __decorateClass (http://localhost:6008/src/my-element.ts?t=1651908414168:7:57)
    at http://localhost:6008/src/my-element.ts?t=1651908414168:50:13
```

The expected result should be: `[vite] hmr update /src/my-element.ts `

### Link to Minimal Reproducible Example

https://github.com/boeto/test-vite-lit-storybook-story-store-V7

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Web components cannot use HMR, according to https://github.com/storybookjs/storybook/tree/master/app/web-components#setup-page-reload-via-hmr.  I'll take a look at the storyStoreV7 issue.

**Comment by boeto** [comment]
@IanVS LGTM 🎉  Thank you !!!
