### ISSUE TITLE
[Bug] Breaks `getStringWidth` from `@visx/text`

### ISSUE THREAD

**Issue by dhess** [storybookjs/builder-vite#374]
### What version of `vite` are you using?

2.9.8

### System info and storybook versions

Environment Info:
```
  System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.15.0 - /nix/store/jir78fsqgcrr2kgyifkydy9drchzcbr1-nodejs-16.15.0/bin/node
    Yarn: 1.22.18 - /nix/store/q8gc8qsaakhcxa74kx0dkb8knms6p3qi-yarn-1.22.18/bin/yarn
    npm: 8.5.5 - /nix/store/jir78fsqgcrr2kgyifkydy9drchzcbr1-nodejs-16.15.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 100.0
    Safari: 15.4

    "@storybook/addon-actions": "^6.4.22",
    "@storybook/addon-essentials": "^6.4.22",
    "@storybook/addon-links": "^6.4.22",
    "@storybook/react": "^6.4.22",
```

### Describe the Bug

We've been using `storybook-builder-vite` with great success on our project for at least 6 months. I discovered a few days ago that it had been replaced with this plugin. I was able to get `@storybook/builder-vite` up and running in a very short amount of time, so thank you for your work.

Everything appears to be working after the upgrade except for one issue that is very mysterious. We use Visx to draw some graphs, and upon startup, the Storybook story for these Visx components is not rendering the label on the nodes in the graph correctly &mdash; the nodes are too small and are cutting off the text of their labels. Before upgrading to `@storybook/builder-vite`, this all worked fine with `storybook-builder-vite`.

We tracked down the issue to `@visx/text`'s `getStringWidth` function returning `0` for these node labels:

https://github.com/airbnb/visx/blob/master/packages/visx-text/src/util/getStringWidth.ts

We use this function as a heuristic for deciding how large to make the nodes in the graph, so that they circumscribe the text of their labels.

Then we noticed that if we just change the label to a different string via our story's control for the label text, the node renders properly and circumscribes the label text. Reverting the label back to its original value causes the problem to appear again.

After some further digging, we figured out what's going on:

1. The first time we render the Visx component in Storybook, all of the calls to `getStringWidth` return `0` due to this this call to `getComputedTextLength`:

https://github.com/airbnb/visx/blob/5ea2499234a375425027e38a7d53d78fad29e65b/packages/visx-text/src/util/getStringWidth.ts#L24

2. `getStringWidth` memoizes that value (`0`). This is why every time you switch the text value back to its original value in the story, it renders incorrectly again.

3. All subsequent calls to `getComputedTextLength` with labels that are different than the original labels return the proper length and there are no issues (e.g., after adding a new node to the graph with a new label, or after changing the original labels via the Storybook controls).

As we've made no other changes to our code, nor to any other dependencies other than switching from `storybook-builder-vite` to `@storybook/builder-vite`, we've narrowed the cause down to `@storybook/builder-vite`. Unfortunately that's as far as I can get with my knowledge about Vite, Storybook, and this plugin. My only thought is that `getStringWidth` renders an offscreen SVG containing the text and uses that to measure the rendered text length, and somehow with `@storybook/builder-vite` that technique does not work the first time the component is rendered. This seems like the sort of thing that happens when there's a race condition, but I'm just guessing wildly.

Note that the problem does not appear to be related to HMR. If we build the Storybook using `build-storybook` and then publish it to Chromatic, the problem manifests there, as well.

Unfortunately the repo exhibiting this issue is proprietary and the code that uses Visx is non-trivial, so I'm not able to make a repro case at this time.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Hi, without a reproduction or something I can look at, this is going to be very difficult to help troubleshoot.  One idea I have, is to try downgrading `@storybook/builder-vite` to older versions, to see if you can narrow down the version when the bug started happening.  Version 0.1.23 of `@storybook/builder-vite` is the same as version 0.1.23 of `storybook-builder-vite`, so you can start there as a sanity check to be sure this is indeed related to this package.

**Comment by dhess** [comment]
For unrelated reasons, we've switched to `pnpm` from `yarn`, and this issue has gone away in the process, FWIW. Feel free to close it if you like.
