### ISSUE TITLE
[Bug] inject, component ... doesn't work in storyStoreV7

### ISSUE THREAD

**Issue by extrem7** [storybookjs/builder-vite#376]
### What version of `vite` are you using?

2.9.1

### System info and storybook versions

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.1.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 101.0.4951.54
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.39)
  npmPackages:
    @storybook/addon-actions: ^6.4.21 => 6.4.21
    @storybook/addon-docs: ^6.4.21 => 6.4.21
    @storybook/addon-essentials: ^6.4.21 => 6.4.21
    @storybook/addon-links: ^6.4.21 => 6.4.21
    @storybook/builder-vite: ^0.1.27 => 0.1.27
    @storybook/vue3: ^6.4.21 => 6.4.21
```

### Describe the Bug

I enabled storyStoreV7 feature and tried to: register Pinia(inject), register component or directive globally, etc.
But everything going wrong. I have console warnings like: `injection "Symbol(pinia)" not found`, `[Vue warn]: Failed to resolve component: globally-registed-component`...

Disabling storyStoreV7 resolves the problem.

**Comment by IanVS** [comment]
Hi, can you please provide a reproduction of the issue?

**Comment by IanVS** [comment]
Hmmm, moving the line with `import { createPinia } from 'pinia'` up to the top with the other imports seems to have fixed it for me.  Maybe you can try that?  And be sure to `rm -rf node_modules/.cache node_modules/.vite-storybook` before you restart.

**Comment by extrem7** [comment]
I needed to just upgrade `@storybook/builder-vite` from 0.1.27 to 0.1.33. It resolves everything.

Thanks for your work! I'll keep an eye on new releases.
