### ISSUE TITLE
[Bug] Preact TypeScript Story: "ReferenceError: h is not defined"

### ISSUE THREAD

**Issue by maxbeatty** [storybookjs/builder-vite#385]
### What version of `vite` are you using?

2.9.9

### System info and storybook versions

```sh
Environment Info:

  System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.15.0 - ~/Development/src/github.com/maxbeatty/example-storybook-preact-vite/bin/node
    Yarn: 3.2.1 - ~/Development/src/github.com/maxbeatty/example-storybook-preact-vite/bin/yarn
    npm: 8.5.5 - ~/Development/src/github.com/maxbeatty/example-storybook-preact-vite/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: ^6.5.0 => 6.5.0 
    @storybook/addon-docs: ^6.5.0 => 6.5.0 
    @storybook/addon-essentials: ^6.5.0 => 6.5.0 
    @storybook/addon-interactions: ^6.5.0 => 6.5.0 
    @storybook/addon-links: ^6.5.0 => 6.5.0 
    @storybook/builder-vite: ^0.1.34 => 0.1.34 
    @storybook/preact: ^6.5.0 => 6.5.0 
    @storybook/testing-library: ^0.0.11 => 0.0.11 
```

### Describe the Bug

The reproducible example repository has step-by-step commits of the setup including `create-vite` and `npx sb init`. After a hiccup with MDX stories, the generated stories load ([commit](https://github.com/maxbeatty/example-storybook-preact-vite/tree/effed9aa37400cbf9a35fdc0c75fffefd9ec02e6)). Then, adding a simple story using `.tsx` (instead of the generated `.jsx`) errors ([diff](https://github.com/maxbeatty/example-storybook-preact-vite/commit/ea1a5a0c937c7c10826df91ddae34467d5013d71)). I tried using a different `tsconfig.json` configuration for `jsx`, but that failed in a different way ([diff](https://github.com/maxbeatty/example-storybook-preact-vite/commit/b44c07ec315377791925f63c2688c4d10f10455d)) (this is also how the private project that spurred this example is configured).

Given Storybook's and Vite's out-of-the-box support for TypeScript, I expected this new story to work without any additional configuration. Any pointers would be appreciated!

### Link to Minimal Reproducible Example

https://github.com/maxbeatty/example-storybook-preact-vite

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
We don't explicitly handle preact in our vite config, but if you're willing to submit a PR, you can update https://github.com/storybookjs/builder-vite/blob/main/packages/builder-vite/vite-config.ts to add a check for preact, similar to the other framework checks, and add  https://github.com/preactjs/preset-vite to the `plugins`.
