### ISSUE TITLE
[Bug] Missing package @mdx-js/react on scratch build sveltekit + storybook + builder-vite

### ISSUE THREAD

**Issue by MiniKraken-Team** [storybookjs/builder-vite#391]
### What version of `vite` are you using?

2.9.9

### System info and storybook versions

System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    npm: 8.9.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: ^6.5.3 => 6.5.3 
    @storybook/addon-essentials: ^6.5.3 => 6.5.3 
    @storybook/addon-interactions: ^6.5.3 => 6.5.3 
    @storybook/addon-links: ^6.5.3 => 6.5.3 
    @storybook/builder-vite: ^0.1.35 => 0.1.35 
    @storybook/builder-webpack4: ^6.5.3 => 6.5.3 
    @storybook/manager-webpack4: ^6.5.3 => 6.5.3 
    @storybook/svelte: ^6.5.3 => 6.5.3 
    @storybook/testing-library: ^0.0.11 => 0.0.11 

### Describe the Bug

Created a scratch project with Sveltekit(1.0.0-next.335), storybook (6.5.3) and builder-vite.
This project with webpack works fine.

But when starting storybook, I'm presented with the following error:

```
info => Ignoring cached manager due to change in manager config
ERR! Error: [vite-plugin-mdx] "@mdx-js/react" must be installed
ERR!     at resolveImport (/Users/maximehuylebroeck/Documents/Development/storybook-load-API-data-via-loaders/node_modules/vite-plugin-mdx/dist/imports.js:29:23)
ERR!     at Object.assertImportExists (/Users/maximehuylebroeck/Documents/Development/storybook-load-API-data-via-loaders/node_modules/vite-plugin-mdx/dist/imports.js:41:12)
ERR!     at /Users/maximehuylebroeck/Documents/Development/storybook-load-API-data-via-loaders/node_modules/vite-plugin-mdx/dist/transform.js:18:19
ERR!     at Array.map (<anonymous>)
ERR!     at Object.createTransformer (/Users/maximehuylebroeck/Documents/Development/storybook-load-API-data-via-loaders/node_modules/vite-plugin-mdx/dist/transform.js:17:50)
ERR!     at Object.configResolved (/Users/maximehuylebroeck/Documents/Development/storybook-load-API-data-via-loaders/node_modules/vite-plugin-mdx/dist/index.js:46:43)
ERR!     at /Users/maximehuylebroeck/Documents/Development/storybook-load-API-data-via-loaders/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:61561:127
ERR!     at Array.map (<anonymous>)
ERR!     at resolveConfig (/Users/maximehuylebroeck/Documents/Development/storybook-load-API-data-via-loaders/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:61561:35)
ERR!     at async getOptimizeDeps (/Users/maximehuylebroeck/Documents/Development/storybook-load-API-data-via-loaders/node_modules/@storybook/builder-vite/dist/optimizeDeps.js:127:28)
```

### Link to Minimal Reproducible Example

https://github.com/GeForcez/storybook-load-API-data-via-loaders

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Might be related to this? https://github.com/brillout/vite-plugin-mdx/issues/47#issuecomment-1039719119

**Comment by IanVS** [comment]
I think we're perhaps moving away from using `vite-plugin-mdx` (see https://github.com/storybookjs/builder-vite/pull/377), but for now, a workaround is to manually install the package that it can't find:

```
npm i --save-dev @mdx-js/react@1 --force
```

After that, (plus setting the builder and adding a `preview-head.html`) I was able to launch the reproduction correctly.

**Comment by openscript** [comment]
Hi @IanVS 

After installing the dependency `@mdx-js/react@1` I get another error:

```
ERR! Error [ERR_REQUIRE_ESM]: require() of ES Module /workspaces/react-section-dividers/node_modules/@mdx-js/mdx/index.js from /workspaces/react-section-dividers/node_modules/vite-plugin-mdx/dist/imports.js not supported.
ERR! Instead change the require of index.js in /workspaces/react-section-dividers/node_modules/vite-plugin-mdx/dist/imports.js to a dynamic import() which is available in all CommonJS modules.
ERR!     at Object.requireMdx (/workspaces/react-section-dividers/node_modules/vite-plugin-mdx/dist/imports.js:10:12)
ERR!     at Object.createTransformer (/workspaces/react-section-dividers/node_modules/vite-plugin-mdx/dist/transform.js:16:27)
ERR!     at Object.configResolved (/workspaces/react-section-dividers/node_modules/vite-plugin-mdx/dist/index.js:46:43)
ERR!     at /workspaces/react-section-dividers/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:61561:127
ERR!     at Array.map (<anonymous>)
ERR!     at resolveConfig (/workspaces/react-section-dividers/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:61561:35)
ERR!     at async getOptimizeDeps (/workspaces/react-section-dividers/node_modules/@storybook/builder-vite/dist/optimizeDeps.js:127:28)
ERR!     at async createViteServer (/workspaces/react-section-dividers/node_modules/@storybook/builder-vite/dist/vite-server.js:23:23)
ERR!     at async Object.start (/workspaces/react-section-dividers/node_modules/@storybook/builder-vite/dist/index.js:53:20)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/workspaces/react-section-dividers/node_modules/@storybook/core-server/dist/cjs/dev-server.js:207:28)
ERR!     at async buildDevStandalone (/workspaces/react-section-dividers/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/workspaces/react-section-dividers/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)
```

Any idea how to fix this? Thank you! :)

**Comment by IanVS** [comment]
Can you check to be sure that you didn't accidentally end up with version 2 of @mdx-js/mdx somehow?  

```
npm ls @mdx-js/mdx
```

**Comment by openscript** [comment]
You are right.. `vite-plugin-mdx` is using version 2:

```
react-section-dividers@0.4.10 /workspaces/react-section-dividers
├─┬ @storybook/addon-docs@6.5.3
│ └─┬ @storybook/mdx1-csf@0.0.1-canary.1.867dcd5.0
│   └── @mdx-js/mdx@1.6.22
└─┬ @storybook/builder-vite@0.1.35
  ├── @mdx-js/mdx@1.6.22
  └─┬ vite-plugin-mdx@3.5.10
    └── @mdx-js/mdx@2.1.1
```

So I've tried to override it in my `package.json`:

```
  "overrides": {
    "vite-plugin-mdx": {
      "@mdx-js/mdx": "^1.6.22"
    }
  }
```
.. but this leads to:

```
react-section-dividers@0.4.10 /workspaces/react-section-dividers
├─┬ @storybook/addon-docs@6.5.3
│ └─┬ @storybook/mdx1-csf@0.0.1-canary.1.867dcd5.0
│   └── @mdx-js/mdx@1.6.22
└─┬ @storybook/builder-vite@0.1.35
  ├── @mdx-js/mdx@1.6.22
  └─┬ vite-plugin-mdx@3.5.10
    └── @mdx-js/mdx@2.1.1 invalid: "^1.6.22" from node_modules/vite-plugin-mdx
```

**Comment by openscript** [comment]
It seems like this only happens when you are on React 18?

**Comment by openscript** [comment]
> Can confirm on `React 18` after installing `@mdx-js/react` normally breaks storybook, but this: [#391 (comment)](https://github.com/storybookjs/builder-vite/issues/391#issuecomment-1132124411) helps and it boots up.

You are right. I've just tested it again and it seems to work now.

**Comment by mszekiel** [comment]
> > Can confirm on `React 18` after installing `@mdx-js/react` normally breaks storybook, but this: [#391 (comment)](https://github.com/storybookjs/builder-vite/issues/391#issuecomment-1132124411) helps and it boots up.
> 
> You are right. I've just tested it again and it seems to work now.

But on the other hand it's problematic when it comes to `npm i` and `--force` is needed unfortunately :(  With my dependencies at least.

**Comment by shilman** [comment]
@IanVS There was a missing dep in `@storybook/mdx1-csf` which I fixed yesterday. Perhaps upgrading to the latest would fix this issue?

https://github.com/storybookjs/mdx1-csf/releases/tag/v0.0.2

**Comment by IanVS** [comment]
Right now we're not using `@storybook/mdx1-csf` at all, but there's a PR that would use it.

**Comment by dohooo** [comment]
WOW! I SOLVED! 

<img width="1886" alt="image" src="https://user-images.githubusercontent.com/32405058/170729696-00d8d341-c584-48ed-b778-4886f02b3bb3.png">

**Comment by tigrr** [comment]
I am having this error, even though I don't use React or Preact, neither do I use MDX.
