### ISSUE TITLE
[Bug] build error with the 'mock-core-js' plugin

### ISSUE THREAD

**Issue by l1shu** [storybookjs/builder-vite#412]
### What version of `vite` are you using?

0.1.36

### System info and storybook versions

Environment Info:

  System:
    OS: Linux 5.4 Tencent tlinux 2.6
    CPU: (16) x64 AMD EPYC 7K62 48-Core Processor
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^6.5.6 => 6.5.6 
    @storybook/addon-links: ^6.5.6 => 6.5.6 
    @storybook/addons: ^6.5.6 => 6.5.6 
    @storybook/builder-vite: ^0.1.36 => 0.1.36 
    @storybook/testing-library: ^0.0.11 => 0.0.11 
    @storybook/theming: ^6.5.6 => 6.5.6 
    @storybook/vue3: ^6.5.6 => 6.5.6 

### Describe the Bug

when I build, occurs an error:
<img width="988" alt="image" src="https://user-images.githubusercontent.com/48285873/174050996-39dcea1f-d44e-468c-9b88-d9b717a63448.png">

I found the reason is the `mock-core-js` plugin impoted by `@storybook/builder-vite`,and it transforms the path which includes the 'core-js' and turns into empty string
<img width="643" alt="image" src="https://user-images.githubusercontent.com/48285873/174051155-b836b4f2-c5c3-4be1-9ed6-a2e1dfa6daff.png">

why need this plugin? can it removed?

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by unicornware** [comment]
[this][1] issue may be of some help to you!

[1]: https://github.com/storybookjs/builder-vite/issues/448

**Comment by IanVS** [comment]
Thanks everyone. A fix for this has been released in @storybook/builder-vite https://github.com/storybookjs/builder-vite/discussions/462. You can remove the workaround from your vite config once you upgrade. And please let us know if you hit any problems.
