### ISSUE TITLE
Compiled storybook shows nested iframes

### ISSUE THREAD

**Issue by pussyslain** [storybookjs/builder-vite#442]
### What version of `vite` are you using?

3.0.0

### System info and storybook versions

Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz     
  Binaries:
    Node: 14.19.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - ~\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.49)
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9
    @storybook/addon-essentials: ^6.5.9 => 6.5.9
    @storybook/addon-interactions: ^6.5.9 => 6.5.9
    @storybook/addon-links: ^6.5.9 => 6.5.9
    @storybook/builder-vite: ^0.2.0 => 0.2.0
    @storybook/react: ^6.5.9 => 6.5.9
    @storybook/testing-library: ^0.0.13 => 0.0.13

### Describe the Bug

Running story locally work fine. 

However, once I try to build the static files using `yarn build-storybook`, this is what it shows:
![image](https://user-images.githubusercontent.com/66193229/178986524-0cb4962c-ffd6-43aa-aa0e-fb01b92cea45.png)

Upon checking the logs, this is what it shows
![image](https://user-images.githubusercontent.com/66193229/178986568-d3ebbd98-5dac-4957-9236-7b49807658d3.png)

Here what my `vite.config.ts`:
```ts
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import svgr from 'vite-plugin-svgr';
import tsconfigPaths from 'vite-tsconfig-paths';

import optimizationPersist from 'vite-plugin-optimize-persist';
import pkgConfig from 'vite-plugin-package-config';
import graphql from '@rollup/plugin-graphql';
import eslintPlugin from '@nabla/vite-plugin-eslint';

// https://vitejs.dev/config/
export default defineConfig({
  // This changes the out put dir from dist to build
  // comment this out if that isn't relevant for your project
  resolve: {
    alias: {
      // https://github.com/aws-amplify/amplify-ui/issues/268#issuecomment-953375909
      './runtimeConfig': './runtimeConfig.browser',
    },
  },
  build: {
    outDir: 'build',
  },
  // @ts-ignore
  test: {
    globals: true,
    testTimeout: 20000,
    environment: 'jsdom',
    include: ['src/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
  },
  server: {
    host: true,
    port: 3000,
  },
  plugins: [
    react(),
    svgr(),
    tsconfigPaths(),
    pkgConfig({
      field: 'vite',
      packageJsonPath: 'vite-deps.json',
    }),
    optimizationPersist(),
    graphql(),
    eslintPlugin({
      eslintOptions: {
        overrideConfigFile: './.eslintrc-ide.json',
      },
    }),
  ],
});

```

### Link to Minimal Reproducible Example

https://github.com/pussyslain/storybook-vite-build-issue-repro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Thanks for the reproduction.  I cloned, installed, built storybook, and launched it using `npx http-server ./storybook-static`, and did not see any problems: 

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/4616705/179005525-fa9de88f-de2c-4ecd-8712-e5ba1ae1b1f9.png">

What are you using to preview the built storybook?

**Comment by pussyslain** [comment]
@IanVS  I see. I am using `serve -s storybook-static` for preview. Probably need additional configuration to make it work.

`http-server` works for me as well. Thank you

**Comment by IanVS** [comment]
:+1:
