### ISSUE TITLE
[Bug] Problems with vue-class-component

### ISSUE THREAD

**Issue by juztinlazaro** [storybookjs/builder-vite#450]
### What version of `vite` are you using?

  "vite": "^2.9.14",

### System info and storybook versions

System: 
  Windows 10
  
Browser: 
 Chrome

Node  v16.15.0

"@storybook/addon-actions": "^6.5.9",
    "@storybook/addon-essentials": "^6.5.9",
    "@storybook/addon-interactions": "^6.5.9",
    "@storybook/addon-links": "^6.5.9",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/builder-vite": "^0.1.39",
    "@storybook/builder-webpack4": "^6.5.9",
    "@storybook/manager-webpack4": "^6.5.9",
    "@storybook/testing-library": "^0.0.13",
    "@storybook/vue3": "^6.5.9",
    "@types/node": "*",
    "@vitejs/plugin-vue": "^2.3.3",
    "babel-loader": "^8.2.5",
    "sass": "^1.35.2",
    "vite": "^2.9.14",
    "vue-loader": "^16.8.3",
    "vue-property-decorator": "^9.1.2"

### Describe the Bug

When i use class component I'm having an error 

![image](https://user-images.githubusercontent.com/10995629/179670726-9280ecdd-10c0-46c9-8c47-5d2022f7425e.png)

```
[vite] Internal server error: Cannot read properties of undefined (reading 'length')
```

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Hi, can you please provide some more details and a reproduction?  I'm not familiar with vue-class-component.  Is that component working fine in your vue app, but not in storybook?  Does it work when using the default webpack builder for storybook (i.e. removing the `core.builder` setting in `main.js`?

**Comment by juztinlazaro** [comment]
@IanVS yes, its working with my application but not in storybook, give me time will try to create a repo. or codesandbox thank you

**Comment by IanVS** [comment]
Thank you!

**Comment by IanVS** [comment]
It looks like vue-class-component is for vue 2 (https://github.com/vuejs/vue-class-component/blob/16433462b40aefecc030919623f17b0ec9afe61c/package.json#L47).  But the vite-builder only supports vue 3.  There's a fork that supports vue 2: https://github.com/djaler/storybook-builder-vite-vue2.
