### ISSUE TITLE
[Bug] cached startup of storybook shows vite entrypoint

### ISSUE THREAD

**Issue by pmelab** [storybookjs/builder-vite#454]
### What version of `vite` are you using?

3.0.0

### System info and storybook versions

  System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.16.0 - ~/.volta/tools/image/node/16.16.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.11.0 - ~/.volta/tools/image/node/16.16.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Edge: 103.0.1264.62
    Firefox: 102.0.1
    Safari: 15.3
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9
    @storybook/addon-essentials: ^6.5.9 => 6.5.9
    @storybook/addon-interactions: ^6.5.9 => 6.5.9
    @storybook/addon-links: ^6.5.9 => 6.5.9
    @storybook/builder-vite: ^0.2.0 => 0.2.0
    @storybook/react: ^6.5.9 => 6.5.9
    @storybook/testing-library: ^0.0.13 => 0.0.13

### Describe the Bug

When creating a new project according to the documentation ...

```
npm create vite@latest # follow the prompts
npx sb init --builder @storybook/builder-vite && npm run storybook
```

... everything is fine on the initial startup of storybook. But when stopping and restarting it, port 6006 binds to the vite app instead. When clearing the cache folder it works again one time.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Hi, this is the same issue as https://github.com/storybookjs/builder-vite/issues/446, and will be fixed as soon as I can release a new version.  Thanks for the report.
