### ISSUE TITLE
[Bug] Can't see any stories files

### ISSUE THREAD

**Issue by Drew11** [storybookjs/builder-vite#458]
### What version of `vite` are you using?

"vite": "^3.0.0"

### System info and storybook versions

"devDependencies": {
    "@babel/core": "^7.18.9",
    "@joshwooding/vite-plugin-react-docgen-typescript": "^0.0.5",
    "@rollup/plugin-alias": "^3.1.9",
    "@storybook/addon-actions": "^6.5.9",
    "@storybook/addon-backgrounds": "^6.5.9",
    "@storybook/addon-docs": "^6.5.9",
    "@storybook/addon-essentials": "^6.5.9",
    "@storybook/addon-interactions": "^6.5.9",
    "@storybook/addon-links": "^6.5.9",
    "@storybook/addon-measure": "^6.5.9",
    "@storybook/addon-outline": "^6.5.9",
    "@storybook/addons": "^6.5.9",
    "@storybook/builder-vite": "^0.2.0",
    "@storybook/channel-postmessage": "^6.5.9",
    "@storybook/channel-websocket": "^6.5.9",
    "@storybook/client-api": "^6.5.9",
    "@storybook/client-logger": "^6.5.9",
    "@storybook/preview-web": "^6.5.9",
    "@storybook/react": "^6.5.9",
    "@storybook/testing-library": "^0.0.13",
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "@typescript-eslint/parser": "^5.30.7",
    "@vitejs/plugin-react": "^2.0.0",
    "autoprefixer": "^10.4.7",
    "babel-loader": "^8.2.5",
    "eslint": "^8.20.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-typescript-prettier": "^5.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "patch-package": "^6.4.7",
    "postcss": "^8.4.14",
    "postcss-load-config": "^4.0.1",
    "prettier": "^2.7.1",
    "tailwindcss": "^3.1.6",
    "tsconfig-paths-webpack-plugin": "^3.5.2",
    "typescript": "^4.7.4",
    "vite": "^3.0.0"
  }

### Describe the Bug

Hello , i'm trying create starter vite-react-ts-eslint-storybook
for test i create small component bButton, and stories Button.stories.ts
here my files :

_./storybook/main.js_
```
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/addon-docs'
  ],
  framework: '@storybook/react',
  core: {
    builder: '@storybook/builder-vite'
  },

  features: {
    storyStoreV7: true
  },
}
```

_vite.config.ts_
```
import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'path'
import tsconfigPaths from 'vite-tsconfig-paths'

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, `${__dirname}/vars`, '')
  return {
    envDir: `./vars`,
    envPrefix: 'ENV',
    plugins: [react(), tsconfigPaths()],
    base: '',
    server: {
      port: env.DEV_PORT
    },
  }
})

```

_tsconfig.json_
```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": true,
    "skipLibCheck": false,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": ["./src"]
}
```

_.babelrc_
```
{
  "presets": ["@babel/preset-env", "@babel/preset-typescript"]
}
```

_Button.stories.tsx_

```
import React from 'react'
import { ComponentStory, ComponentMeta } from '@storybook/react'
import { Button } from './button'

export default {
  /* 👇 The title prop is optional.
   * See https://storybook.js.org/docs/react/configure/overview#configure-story-loading
   * to learn how to generate automatic titles
   */
  title: 'Button',
  component: Button
} as ComponentMeta<typeof Button>


export const Primary: ComponentStory<typeof Button> = (args) => <Button {...args} />
```

![image](https://user-images.githubusercontent.com/13404293/180652255-59abcdb9-3e09-4867-8ac2-aa0c2c8d5beb.png)

![image](https://user-images.githubusercontent.com/13404293/180652475-888a17e9-9b0e-4ff8-b6fe-40a9bbdce160.png)

maybe i do something wrong with alias or paths?

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Drew11** [comment]
[IanVS](https://github.com/IanVS) here : https://github.com/Drew11/full-stack-react-nest

**Comment by IanVS** [comment]
I cloned your repo and got a different error about `@mdx-js/react` not being found.  I think this is because of the way pnpm is resolving dependencies.  Manually installing it with `pnpm i @mdx-js/react@1` solved the issue.  Try that out, and if you still have trouble, try deleting your `node_modules/.cache` and `node_modules/.vite-storybook` caches, and then run storybook again.

**Comment by Drew11** [comment]
Thx , you try run storybook in my projeсt, he sees stories files when run on localhost:6006?

i not have errors , but still storybook not see any files with .stories.
also i try you variants delete cache, and remove node_modules and install again another package-manager like yarn
still not have result :(

when install storybook he automatically generate examples
<img width="192" alt="image" src="https://user-images.githubusercontent.com/13404293/180661767-79e477bf-3678-4438-b85b-f72d73e74dff.png">

but this examples he can't see , don't know why
<img width="604" alt="image" src="https://user-images.githubusercontent.com/13404293/180662521-33d8bd30-f5f4-48a8-a4f0-86b5b3293a84.png">

**Comment by IanVS** [comment]
Yep, once I installed that mdx dependency, I ran `pnpm run storybook` and I saw a button story and a switch story, in addition to the standard ones added by storybook init.

**Comment by IanVS** [comment]
I see in your example you are opening the page by the internal ip address. Is there any difference I'd you use localhost instead?

**Comment by Drew11** [comment]
[IanVS](https://github.com/IanVS) thank you , finally it's works 
 i cloned from my repo install, and got mdx error , add mdx and now work
 
 why i  not got it MDX error in local don't know, this strange 
 
 maybe my project is in a folder name with square brackets and this not good for install package  like D:/work/[drew]/[projects]/my-project

**Comment by IanVS** [comment]
I'm not sure why it wasn't working, but glad you're in good shape now.
