### ISSUE TITLE
[Bug]  Can't build storybook, TypeError: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by DarioRega** [storybookjs/builder-vite#466]
### What version of `vite` are you using?

3.0.0

### System info and storybook versions

  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addon-viewport: ^6.5.9 => 6.5.9 
    @storybook/builder-vite: ^0.2.2 => 0.2.2 
    @storybook/preset-scss: ^1.0.3 => 1.0.3 
    @storybook/react: ^6.5.9 => 6.5.9 

### Describe the Bug

I've started my project with 
- npm create vite@latest my-vue-app -- --template react-ts
- npx sb init --builder @storybook/builder-vite

I can run storybook locally without any problems, but once i want to build it, it says:
```
/Users/dariorega/Desktop/coding/hackventures/styleguide/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:143
throw new TypeError(
^

TypeError: The 'compilation' argument must be an instance of Compilation
at Function.getCompilationHooks (/Users/dariorega/Desktop/coding/hackventures/styleguide/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:143:10)
at /Users/dariorega/Desktop/coding/hackventures/styleguide/node_modules/terser-webpack-plugin/dist/index.js:566:67
at SyncHook.eval [as call] (eval at create (/Users/dariorega/Desktop/coding/hackventures/styleguide/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:85:1)
at SyncHook.lazyCompileHook (/Users/dariorega/Desktop/coding/hackventures/styleguide/node_modules/tapable/lib/Hook.js:154:20)
at Compiler.newCompilation (/Users/dariorega/Desktop/coding/hackventures/styleguide/node_modules/@storybook/manager-webpack4/node_modules/webpack/lib/Compiler.js:631:26)
at /Users/dariorega/Desktop/coding/hackventures/styleguide/node_modules/@storybook/manager-webpack4/node_modules/webpack/lib/Compiler.js:667:29
at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dariorega/Desktop/coding/hackventures/styleguide/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
at AsyncSeriesHook.lazyCompileHook (/Users/dariorega/Desktop/coding/hackventures/styleguide/node_modules/tapable/lib/Hook.js:154:20)
at Compiler.compile (/Users/dariorega/Desktop/coding/hackventures/styleguide/node_modules/@storybook/manager-webpack4/node_modules/webpack/lib/Compiler.js:662:28)
at /Users/dariorega/Desktop/coding/hackventures/styleguide/node_modules/@storybook/manager-webpack4/node_modules/webpack/lib/Compiler.js:321:11
```
Im using this project to create a component library, i have a config part in package json and vite config to actually build the package library and another one is to work on the component with storybook. I use storybook as well to publish the styleguide to a webpage.

This is my package.json content
```
{
	"name": "@dariorega/styleguide",
	"private": true,
	"version": "0.0.0",
	"author": "DarioRega",
	"license": "ISC",
	"publishConfig": {
		"registry": "https://npm.pkg.github.com/component-library"
	},
	"scripts": {
		"build": "run-p build:*",
		"build:scripts": "vite build",
		"build:types": "tsc --emitDeclarationOnly && tsc-alias",
		"lint:validate": "eslint ./src --ext .jsx,.js,.ts,.tsx --quiet --ignore-path ./.gitignore",
		"lint:check-format": "prettier --loglevel warn \"./**/*.{js,jsx,ts,tsx,css,md,json}\" ",
		"lint": "npm run lint:check-format && npm run lint:validate",
		"lint:fix": "npm run lint:validate --fix && npm run lint:check-format --write",
		"type-check": "tsc",
		"test": "exit 0",
		"prepare": "husky install",
		"storybook": "start-storybook -p 6006",
		"build:storybook": "build-storybook -- -o styleguide-dist --no-manager-cache"
	},
	"peerDependencies": {
		"react": "^18.2.0",
		"react-dom": "^18.2.0",
		"styled-components": "^5.3.5"
	},
	"devDependencies": {
		"@babel/core": "^7.18.9",
		"@storybook/addon-actions": "^6.5.9",
		"@storybook/addon-essentials": "^6.5.9",
		"@storybook/addon-interactions": "^6.5.9",
		"@storybook/addon-links": "^6.5.9",
		"@storybook/addon-postcss": "^2.0.0",
		"@storybook/addon-viewport": "^6.5.9",
		"@storybook/builder-vite": "^0.2.2",
		"@storybook/preset-scss": "^1.0.3",
		"@storybook/react": "^6.5.9",
		"@types/node": "^18.6.2",
		"@types/react": "^18.0.15",
		"@types/react-dom": "^18.0.6",
		"@types/styled-components": "^5.1.25",
		"@typescript-eslint/eslint-plugin": "^5.31.0",
		"@typescript-eslint/parser": "^5.31.0",
		"@vitejs/plugin-react": "^2.0.0",
		"autoprefixer": "^10.4.7",
		"babel-loader": "^8.2.5",
		"eslint": "^8.20.0",
		"eslint-config-prettier": "^8.5.0",
		"eslint-plugin-import": "^2.26.0",
		"eslint-plugin-jsx-a11y": "^6.6.1",
		"eslint-plugin-prettier": "^4.2.1",
		"eslint-plugin-react": "^7.30.1",
		"eslint-plugin-simple-import-sort": "^7.0.0",
		"eslint-plugin-storybook": "^0.6.1",
		"eslint-plugin-unused-imports": "^2.0.0",
		"husky": "^8.0.1",
		"npm-run-all": "^4.1.5",
		"postcss": "^8.4.14",
		"prettier": "^2.7.1",
		"react": "^18.2.0",
		"react-dom": "^18.2.0",
		"sass": "^1.54.0",
		"styled-components": "^5.3.5",
		"tailwindcss": "^3.1.6",
		"tsc-alias": "^1.7.0",
		"typescript": "^4.6.4",
		"vite": "^3.0.0",
		"vite-plugin-dts": "^1.4.0"
	},
	"main": "dist/index.cjs.js",
	"module": "dist/index.es.js",
	"types": "dist/index.d.ts",
	"exports": {
		".": {
			"require": "./dist/index.cjs.js",
			"import": "./dist/index.es.js"
		},
		"./dist/style.css": "./dist/style.css"
	},
	"sideEffects": false,
	"files": [
		"dist"
	]
}
```

Strange thing is, i do not have any obvious dependecy to webpack, it seems its storybook that is using them and bring conflict.

Here is my repo (branch vite) where you can see my viteconfig and my  .storybook folder with some configs
https://github.com/DarioRega/component-lib-test/tree/vite

Thanks in advance and let me know if need more informations

### Link to Minimal Reproducible Example

https://github.com/DarioRega/component-lib-test/tree/vite

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
This looks like the same issue as https://github.com/storybookjs/builder-vite/issues/463.  Do you have webpack 5 installed in your proejct?

**Comment by DarioRega** [comment]
Hey, Thanks for your quick reply, really appreciated

When i run the _npm ls webpack_ i have as well a lot of webpack 5 references in the nodes modules, however in my project there is no webpack or any references to it installed.

I've started with the vit init and then added the storybook builder vite with the npx command

I can add the npm ls webpack output if you want, or is there anywhere else i may have forgotten ?

**Comment by IanVS** [comment]
It looks like you still have `babel-loader` in your `package.json`, that could be pulling in webpack perhaps.  You could try `npm why webpack` to find out why webpack5 is being included.

**Comment by DarioRega** [comment]
Added the output of:

npm ls webpack:
```
├─┬ @storybook/addon-essentials@6.5.9
│ └─┬ @storybook/core-common@6.5.9
│   ├─┬ fork-ts-checker-webpack-plugin@6.5.2
│   │ └── webpack@5.74.0 deduped
│   └─┬ webpack@4.46.0
│     └─┬ terser-webpack-plugin@1.4.5
│       └── webpack@4.46.0 deduped
├─┬ @storybook/addon-postcss@2.0.0
│ ├─┬ css-loader@3.6.0
│ │ └── webpack@5.74.0 deduped
│ ├─┬ postcss-loader@4.3.0
│ │ └── webpack@5.74.0 deduped
│ └─┬ style-loader@1.3.0
│   └── webpack@5.74.0 deduped
├─┬ @storybook/preset-scss@1.0.3
│ └─┬ sass-loader@13.0.2
│   └── webpack@5.74.0 deduped
├─┬ @storybook/react@6.5.9
│ ├─┬ @pmmmwh/react-refresh-webpack-plugin@0.5.7
│ │ └── webpack@5.74.0 deduped
│ ├─┬ @storybook/core@6.5.9
│ │ ├─┬ @storybook/core-client@6.5.9
│ │ │ └── webpack@5.74.0 deduped
│ │ ├─┬ @storybook/core-server@6.5.9
│ │ │ ├─┬ @storybook/builder-webpack4@6.5.9
│ │ │ │ ├─┬ file-loader@6.2.0
│ │ │ │ │ └── webpack@5.74.0 deduped
│ │ │ │ ├─┬ html-webpack-plugin@4.5.2
│ │ │ │ │ └── webpack@4.46.0 deduped
│ │ │ │ ├─┬ postcss-loader@4.3.0
│ │ │ │ │ └── webpack@4.46.0 deduped
│ │ │ │ ├─┬ raw-loader@4.0.2
│ │ │ │ │ └── webpack@5.74.0 deduped
│ │ │ │ ├─┬ terser-webpack-plugin@4.2.3
│ │ │ │ │ └── webpack@5.74.0 deduped
│ │ │ │ ├─┬ url-loader@4.1.1
│ │ │ │ │ └── webpack@5.74.0 deduped
│ │ │ │ ├─┬ webpack-dev-middleware@3.7.3
│ │ │ │ │ └── webpack@5.74.0 deduped
│ │ │ │ ├─┬ webpack-filter-warnings-plugin@1.2.1
│ │ │ │ │ └── webpack@4.46.0 deduped
│ │ │ │ └─┬ webpack@4.46.0
│ │ │ │   └─┬ terser-webpack-plugin@1.4.5
│ │ │ │     └── webpack@4.46.0 deduped
│ │ │ ├─┬ @storybook/manager-webpack4@6.5.9
│ │ │ │ ├─┬ html-webpack-plugin@4.5.2
│ │ │ │ │ └── webpack@4.46.0 deduped
│ │ │ │ └─┬ webpack@4.46.0
│ │ │ │   └─┬ terser-webpack-plugin@1.4.5
│ │ │ │     └── webpack@4.46.0 deduped
│ │ │ └─┬ webpack@4.46.0
│ │ │   └─┬ terser-webpack-plugin@1.4.5
│ │ │     └── webpack@4.46.0 deduped
│ │ └── webpack@5.74.0 deduped
│ ├─┬ @storybook/react-docgen-typescript-plugin@1.0.2-canary.6.9d540b91e815f8fc2f8829189deb00553559ff63.0
│ │ └── webpack@5.74.0 deduped
│ └─┬ webpack@5.74.0
│   └─┬ terser-webpack-plugin@5.3.3
│     └── webpack@5.74.0 deduped
└─┬ babel-loader@8.2.5
  └── webpack@5.74.0 deduped
```
[why.log](https://github.com/storybookjs/builder-vite/files/9213464/why.log)


Added as well the npm why webpack as log ifle

I even removed all babel mention in my package.json, i still have that error. I apologize in advance but i may be a bit lost there, i might understand that this might be webpack causing it, but many storybook addons are actually using it, even the core and in my project i don't have a direct reference to it.

Do you think adding a resolutions' property in my package.json could actually help or any webpack references would just break everything ?

Im sorry i can't be of much help...

**Comment by bill-z** [comment]
fwiw, I've spent the last day looking at this same error when building a production Storybook for my React/Typescript component library.  (In my case I also have cypress installed which needs a webpack dev server.)

**Comment by IanVS** [comment]
@bill-z @DarioRega have either of you tried installing webpack@4 directly in your project?

**Comment by bill-z** [comment]
Updating the storybook config to use webpack5 appears to resolve the issue for my project.  (per [docs](https://storybook.js.org/docs/react/builders/webpack#webpack-5))

**Comment by IanVS** [comment]
That's fine, but keep in mind you'll no longer be using the vite builder if you do that.  If the rest of your app is being bundled with Vite, I recommend trying to stick with the vite builder for storybook, to avoid any potential differences between your stories and your app.

**Comment by altarrok** [comment]
My whole app is using vite but storybook still has webpack dependencies, is there a way to get rid of all webpack dependencies?

**Comment by IanVS** [comment]
Starting in storybook 7 there will be no more webpack installed.

**Comment by DarioRega** [comment]
@IanVS i wasn't able to reproduce, seems like a hell of nested dependencies with that webpack... Can't wait for storybook 7 !
Thanks for your support, i will close that issue in the meantime

**Comment by dudek-igor** [comment]
Hello everyone
the bug was created by diffrent webpack version in one project.
For me, using `npm install --legacy-peer-deps` solved the problem!

Looking forward for storybook v7 !
