### ISSUE TITLE
[Bug] Typescript compilation errors

### ISSUE THREAD

**Issue by jgunzelman88** [storybookjs/builder-vite#468]
### What version of `vite` are you using?

3.0.4

### System info and storybook versions

  System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-vite: ^0.2.2 => 0.2.2 
    @storybook/svelte: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.13 

### Describe the Bug

```
9:01:45 AM [vite] Internal server error: /Users/jgunzelman/Workspaces/personal/tcg-case/src/components/CardCaseCorner.svelte:7:17 Unexpected token
  Plugin: vite-plugin-svelte
  File: /Users/jgunzelman/Workspaces/personal/tcg-case/src/components/CardCaseCorner.svelte
    5 |      import "../assets/css/smui.css";
    6 |  
    7 |      export let id: number;
                                  ^
    8 |      export let grade: number;
    9 |      export let grader: string;
```

I have searched through all the issues and everyone seems to be having similar issues or magically fixed or said of it's fixed now in the version released a year ago yet still running into this problem.  I really hate software that says just run our initializer in lue of comprehensive documentation when their initializer doesn't work.

### Link to Minimal Reproducible Example

https://github.com/poketrax/tcg-case

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jgunzelman88** [comment]
I'm sorry I am honestly just frustrated in general,  I am blocked like every where i have a new project on bun js that is waiting on issues for then to solve but they are still new.  Anywho Only when running storybook.  Sb loads and when I click on my component I get an unexpected token error.

My project is public https://github.com/poketrax/tcg-case I have the preprocessor defined in my svelte config. and it's linked in the svelte options in main.cjs

**Comment by IanVS** [comment]
I get it, config problems can definitely be frustrating.  

I think I found your problem in your repo.  You're using:

```
	"preprocess": import("../svelte.config.js").preprocess
```

But, since `import()` returns a promise, and it's not being awaited, `svelteOptions.preprocess` is not being set.  One alternative, which, admittedly isn't super-DRY is to require and call `svelte-preprocess` directly:

```js
	preprocess: require('svelte-preprocess')()
```

After making that change, I got a different error about a missing file, but that one looked legitimate.

This is a bit of a temporary solution until storybook 7.0 is released, which will support native ESM config files, which should solve much of the config headaches right now especially when using `type: module` in package.json.

**Comment by jgunzelman88** [comment]
Thanks for the help I managed to get it working I read thought your documentation rather than the story book main documentation and found what I needed.  Storybook proper needs to find a way to coolcated all this.

For any future viewers: here is my main.cjs
`const { mergeConfig } = require('vite');
const preprocess = require('svelte-preprocess');

`const { mergeConfig } = require('vite');
const preprocess = require('svelte-preprocess');

module.exports = {
  async viteFinal(config, { configType }) {
    // return the customized config
    return mergeConfig(config);
  },
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx|svelte)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions"
  ],
  "framework": "@storybook/svelte",
  "core": {
    "builder": "@storybook/builder-vite"
  },
  "svelteOptions": {
    "preprocess": preprocess({
      typescript: true,
      postcss: true,
      sourceMap: true,
    }),
  },
  "features": {
    "storyStoreV7": true
  }
}`
