### ISSUE TITLE
[Bug] React + SB builds, but all stories are empty and throws 404 

### ISSUE THREAD

**Issue by Patrick-Ullrich** [storybookjs/builder-vite#471]
### What version of `vite` are you using?

3.0.4

### System info and storybook versions

  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.14.0 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9
    @storybook/addon-essentials: ^6.5.9 => 6.5.9
    @storybook/addon-interactions: ^6.5.9 => 6.5.9
    @storybook/addon-links: ^6.5.9 => 6.5.9
    @storybook/builder-vite: ^0.2.2 => 0.2.2
    @storybook/react: ^6.5.9 => 6.5.9
    @storybook/testing-library: ^0.0.13 => 0.0.13

### Describe the Bug

React-Ts + Vite

Development works just fine, but when hosting the build, stories show no content and throw a 404.

Local - `yarn storybook`
![Screen Shot 2022-08-01 at 11 13 30 AM](https://user-images.githubusercontent.com/6193042/182205387-e10e37eb-5fea-4769-8e53-1ceb9ceb8f88.png)

Hosted - `yarn build-storybook` output

![Screen Shot 2022-08-01 at 11 14 37 AM](https://user-images.githubusercontent.com/6193042/182205522-1c6ebf99-6f07-41c2-8dab-682404076466.png)
![Screen Shot 2022-08-01 at 11 14 41 AM](https://user-images.githubusercontent.com/6193042/182205529-d879ce83-66f7-4711-ab2a-a75c0170a861.png)

I noticed this first on a larger project, but I get the same with a brand new project.

1. npm create vite@latest (choose react and react-ts)
2. npx sb init --builder @storybook/builder-vite

Go to package.json and remove "type": "module".  (https://github.com/storybookjs/storybook/issues/11587)

3. `yarn storybook` => everything works as expected
4. `yarn build-storybook` => builds fine
5. Host the dist folder.. e.g. I am using a vs code plugin to test - [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)

See second screenshot. 

## Workaround

For now I am using webpack 5 builder for the build... Which is defeating the purpose but only workaround i have so far.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Can you try using `npx http-server ./storybook-static` instead of live server, to see if that plays a role?  

And by the way, you shouldn't need to remove `type: module` from your package.json if you rename the `.storybook/main.js` file to `.storybook/main.cjs`.

**Comment by Patrick-Ullrich** [comment]
Ah... That works. I ran into that issue also in a hosted version, but looking back i must have had something else wrong (not include everything or something...) 

Thanks. 👍
