### ISSUE TITLE
[Bug] HMR does not work, components lose styles

### ISSUE THREAD

**Issue by romeovs** [storybookjs/builder-vite#472]
### What version of `vite` are you using?

3.0.4

### System info and storybook versions

```
  System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 18.7.0 - ~/.config/nodenv/versions/18.7.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.config/nodenv/versions/18.7.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 103.0
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9
    @storybook/addon-essentials: ^6.5.9 => 6.5.9
    @storybook/addon-interactions: ^6.5.9 => 6.5.9
    @storybook/addon-links: ^6.5.9 => 6.5.9
    @storybook/addon-postcss: ^3.0.0-alpha.1 => 3.0.0-alpha.1
    @storybook/builder-vite: ^0.2.2 => 0.2.2
    @storybook/builder-webpack4: ^6.5.9 => 6.5.9
    @storybook/manager-webpack4: ^6.5.9 => 6.5.9
    @storybook/react: ^6.5.9 => 6.5.9
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

### Describe the Bug

Using `@storybook/builder-vite` in the most basic setup, HMR seems to not work in the components.

When I edit `src/button/index.tsx`, I see a message in the browser console:
```
[vite] hot updated: /src/button/index.tsx
```
but nothing actually changes.

When I edit `src/button/styles.module.css`, I see the same message, and the component loses all it's styling.

Am I missing something in my config here? Any help would be appreciated!

### Link to Minimal Reproducible Example

https://github.com/romeovs/storybook-vite-demo

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ayush-seth** [comment]
I am facing the same issue. Any updates on this?

**Comment by IanVS** [comment]
We are pushing hard on storybook 7 which should solve this and many other issues. But I'll try to take a look at this and see if I can figure out what's going on.

**Comment by IanVS** [comment]
I finally took some time to look into this, @romeovs, and found the issue.

You are binding directly to the component, rather than to a `Template` story component.  

You need to use something like this:

```ts
const Template: ComponentStory<typeof Button> = (args) => <Button {...args} />

export const Default: Story<ButtonProps> = Template.bind({})
Default.args = {
  children: "Click Me!",
}
```

Instead, you just had:

```ts
export const Default: Story<ButtonProps> = Button.bind({})
Default.args = {
  children: "Click Me!",
}
```

There are a few other issues with the repo as well, such as using @storybook/addon-postcss@3.0.0-alpha.1 (should be version 2.x) and not adding it to your `addons` in `main.js`.  But the problem I mention above is the reason for HMR not working.
