### ISSUE TITLE
[Bug] absolute links to /assets/

### ISSUE THREAD

**Issue by TommasoAmici** [storybookjs/builder-vite#475]
### What version of `vite` are you using?

3.0.4

### System info and storybook versions

Environment Info:

  System:
    OS: macOS 12.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.16.0 - /usr/local/opt/node@16/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/opt/node@16/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.6
  npmPackages:
    @storybook/addon-a11y: 6.5.9 => 6.5.9
    @storybook/addon-actions: 6.5.9 => 6.5.9
    @storybook/addon-docs: 6.5.9 => 6.5.9
    @storybook/addon-essentials: 6.5.9 => 6.5.9
    @storybook/addon-links: 6.5.9 => 6.5.9
    @storybook/builder-vite: ^0.2.2 => 0.2.2
    @storybook/web-components: 6.5.9 => 6.5.9

### Describe the Bug

Hi, I'm having a small issue with the static build of storybook using vite.

We use storybook for our design system and every time we make a release we store the static storybook in s3 with a structure like this:

```
{BUCKET}/{VERSION}

{BUCKET}/2.5.0
{BUCKET}/2.5.1
{BUCKET}/2.6.0
```

We're considering switching from the webpack builder to the vite builder, but the static output of the vite builder uses absolute links to the `asset/` directory it creates.

For example, this means that when navigating to `{BUCKET}/2.5.0` it looks for assets in `{BUCKET}/assets` instead of `{BUCKET}/2.5.0/assets` and this obviously doesn't work.

I'm not sure if this is something that can be configured, but I'd like to avoid having to search and replace in the build step.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Have you tried setting the `base` config in `viteFinal`?  https://vitejs.dev/config/shared-options.html#base

You could try setting it to `'./'` to make it relative.

**Comment by TommasoAmici** [comment]
Oh, yes, that's it! Thanks for the quick reply 🙂
