### ISSUE TITLE
Missing initializer in const declaration. [Bug] 

### ISSUE THREAD

**Issue by mstachalski** [storybookjs/builder-vite#483]
### What version of `vite` are you using?

3.0.7

### System info and storybook versions

  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.63)
  npmPackages:
    @storybook/addon-actions: ^6.5.10 => 6.5.10
    @storybook/addon-essentials: ^6.5.10 => 6.5.10
    @storybook/addon-interactions: ^6.5.10 => 6.5.10
    @storybook/addon-links: ^6.5.10 => 6.5.10
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/builder-vite: ^0.2.2 => 0.2.2
    @storybook/react: ^6.5.10 => 6.5.10
    @storybook/testing-library: ^0.0.13 => 0.0.13

PS C:\Users\mstachalski\Documents\viteProject> npx sb@next info

Environment Info:

  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.63)
  npmPackages:
    @storybook/addon-actions: ^6.5.10 => 6.5.10
    @storybook/addon-essentials: ^6.5.10 => 6.5.10
    @storybook/addon-interactions: ^6.5.10 => 6.5.10
    @storybook/addon-links: ^6.5.10 => 6.5.10
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/builder-vite: ^0.2.2 => 0.2.2
    @storybook/react: ^6.5.10 => 6.5.10

### Describe the Bug

When I try to convert the main.js in .storybook into a .ts file like in the given example, I get the error 

"Missing initializer in const declaration. [Bug] "

Here is the content of my main.ts:

```
import {StorybookViteConfig} from "@storybook/builder-vite";

const {mergeConfig} = require('vite');
const config: StorybookViteConfig = {
    async viteFinal(config, {configType}) {
        return mergeConfig(config);
    },
    stories: [
        "../src/**/*.stories.mdx",
        "../src/**/*.stories.@(js|jsx|ts|tsx)"
    ],
    addons: [
        "@storybook/addon-links",
        "@storybook/addon-essentials",
        "@storybook/addon-interactions",
        "@storybook/addon-postcss"
    ],
    framework: "@storybook/react",
    core: {
        "builder": "@storybook/builder-vite"
    },
    features: {
        "storyStoreV7": true
    },
    typescript: {
        "check": false,
        "checkOptions": {},
        "reactDocgen": 'react-docgen-typescript',
        "reactDocgenTypescriptOptions": {
            "shouldExtractLiteralValuesFromEnum": true,
            "propFilter": (prop) => (prop.parent ? !/node_modules/.test(prop.parent.fileName) : true),
        },
    },
}

export default config;
```

I'm just setting up this project from scratch. No idea what I'm doing wrong, since clearly the const is initialized.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Does it work correctly if you convert the file to `main.cjs` and use normal commonjs?  I've had lots of problems trying to use typescript in my config files, but the upcoming Storybook 7.0 should support it much better.  So, maybe you can do without TS for a little bit until that's ready?

**Comment by mstachalski** [comment]
Yeah it worked with normal .cjs. I guess I will just use that then :).

**Comment by IanVS** [comment]
I know it's a bummer, but it'll get better soon!

**Comment by joshwooding** [comment]
@mstachalski I think the other fix is to use module.exports like https://github.com/jpmorganchase/uitk/blob/d66316c645ef9c2887dc41dd4dd7c708eec3fcbc/.storybook/main.ts#L64. Going to close this issue since it's not something that we can fix in the vite builder unfortunately
