### ISSUE TITLE
[Bug] vite.createFilter is not function

### ISSUE THREAD

**Issue by do2bly** [storybookjs/builder-vite#513]
### What version of `vite` are you using?

^0.2.4

### System info and storybook versions

System:
OS: macOS 12.2.1
CPU: Apple M1 Pro
Binaries:
Node: 16.13.2 - /usr/local/opt/node@16/bin/node
npm: 8.1.2 - /usr/local/opt/node@16/bin/npm
yarn: 3.2.1
Browsers:
Chrome: 106.0.5249.119

### Describe the Bug

I'm use storybook and @storybook/builder-vite in React project.
I found an error while running the storybook.

![image](https://user-images.githubusercontent.com/49511407/196963121-665e2d06-58fc-4ed1-aa70-7403cd1040f8.png)

my dependencies is this.

```
    "@storybook/addon-actions": "^6.5.12",
    "@storybook/addon-docs": "^6.5.12",
    "@storybook/addon-essentials": "^6.5.12",
    "@storybook/addon-links": "^6.5.12",
    "@storybook/builder-vite": "^0.2.4",
```

.storybook/main.js
```js
module.exports = {
  stories: ["../packages/**/*.stories.tsx"],
  core: {
    builder: "@storybook/builder-vite",
  },
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
  ],
  typescript: {
    reactDocgen: false,
  },
}

```

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
This likely means that you have an old version of vite installed. Can you double-check that you're using vite 3 or above?

**Comment by do2bly** [comment]
@IanVS 
I solved this issue by installing vite 3.
Thank you for your advise.
