### ISSUE TITLE
[Bug] build-storybook not working

### ISSUE THREAD

**Issue by unional** [storybookjs/builder-vite#515]
### What version of `vite` are you using?

3.1.0

### System info and storybook versions

Environment Info:

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 105.0.3
    Safari: 16.0
  npmPackages:
    @storybook/addon-actions: ^6.5.12 => 6.5.12 
    @storybook/addon-backgrounds: ^6.5.13 => 6.5.13 
    @storybook/addon-console: ~1.2.3 => 1.2.3 
    @storybook/addon-docs: ^6.5.13 => 6.5.13 
    @storybook/addon-essentials: ^6.5.12 => 6.5.12 
    @storybook/addon-interactions: ^6.5.12 => 6.5.12 
    @storybook/addon-links: ^6.5.12 => 6.5.12 
    @storybook/addon-measure: ^6.5.13 => 6.5.13 
    @storybook/addon-outline: ^6.5.13 => 6.5.13 
    @storybook/addon-storysource: ~6.5.12 => 6.5.12 
    @storybook/addons: ~6.5.12 => 6.5.12 
    @storybook/builder-vite: ^0.2.4 => 0.2.4 
    @storybook/channel-postmessage: ^6.5.13 => 6.5.13 
    @storybook/channel-websocket: ^6.5.13 => 6.5.13 
    @storybook/client-api: ^6.5.13 => 6.5.13 
    @storybook/jest: ~0.0.10 => 0.0.10 
    @storybook/preview-web: ^6.5.12 => 6.5.13 
    @storybook/react: ^6.5.12 => 6.5.12 
    @storybook/test-runner: ~0.7.2 => 0.7.2 
    @storybook/testing-library: ^0.0.13 => 0.0.13

### Describe the Bug

Running `start-storybook`, it is working:

![image](https://user-images.githubusercontent.com/3254987/199362817-ae700730-39e8-4954-b911-d6d1a8a2c5c3.png)

But running `build-storybook`, the resulting site is not working:

![image](https://user-images.githubusercontent.com/3254987/199362870-d8b36b0d-de4e-4597-96c3-4f42555bfcc1.png)

It seems like the bundled code tries to load some file that doesn't exist:

![image](https://user-images.githubusercontent.com/3254987/199362925-470dfed0-ad9f-4dda-a65b-cda4a4f5b006.png)
![image](https://user-images.githubusercontent.com/3254987/199362958-8a148bc8-a5f6-4106-ba1e-10ec438df8a5.png)

Here is my vite config:

```ts
import react from '@vitejs/plugin-react'
import { resolve } from 'node:path'
import { defineConfig } from 'vitest/config'
import { transform } from '@formatjs/ts-transformer'
import typescript from '@rollup/plugin-typescript'
import externals from 'rollup-plugin-node-externals'
import WindiCSS from 'vite-plugin-windicss'

const resolvePath = (str: string) => resolve(__dirname, str)

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react({
      exclude: [/\.stories\.(t|j)sx?$/],
    }),
    { ...externals(), enforce: 'pre' },
    WindiCSS(),
  ],
  build: {
    lib: {
      entry: resolvePath('ts/index.ts'),
      formats: [],
      fileName: 'pats-react-ui'
    },
    rollupOptions: {
      plugins: [
        typescript({
          tsconfig: 'tsconfig.build.json',
          transformers: {
            before: [
              transform({
                overrideIdFn: '[sha512:contenthash:base64:6]',
                ast: true,
              }),
            ],
          },
        }),
      ],
      output: [
        { dir: 'cjs', format: 'cjs', sourcemap: true },
        { dir: 'esm', format: 'es', sourcemap: true }
      ]
    },
    sourcemap: true,
  },
  test: {
    environment: 'jsdom',
    setupFiles: 'scripts/test-setup.ts',
    threads: false, // disable worker threads so that canvas runs in main thread
  },
  resolve: {
    alias: {
      /**
       * Storybook (specifically the interactions addon) requires that we use their
       *   instrumented version of jest-expect. So our storybook does so. To make
       *   these interactions still work in vitest we have @storybook/jest aliased
       *   to resolve to vitest which, critically, exports { expect } as well.
       */
      '@storybook/jest': 'vitest',
    },
  },
})

```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Can you please share how you're starting up your storybook?  Are you using something like `npx http-server storybook-static`?  

Also, can you share your storybook config, particularly your `viteFinal` if you have one?

**Comment by IanVS** [comment]
@JuanjoOrt can you provide any more details that might help with troubleshooting the problem?  I asked a few questions above, but did not get an answer.

**Comment by unional** [comment]
Hi, sorry for the late reply. It turns out it is VS code Live Server issue.

Running with `npx http-server storybook-static` works fine. thx
