### ISSUE TITLE
[Bug] Compatibility with vue 2.7 and @vitejs/plugin-vue2

### ISSUE THREAD

**Issue by AlEsGoGit** [storybookjs/builder-vite#516]
### What version of `vite` are you using?

3.2.0

### System info and storybook versions

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 16.18.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 106.0.3
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.13 
    @storybook/addon-essentials: ^6.5.9 => 6.5.13 
    @storybook/addon-links: ^6.5.9 => 6.5.13 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addons: ^6.5.9 => 6.5.13 
    @storybook/builder-vite: 0.1.x => 0.1.41 
    @storybook/theming: ^6.5.9 => 6.5.13 
    @storybook/vue: ^6.5.9 => 6.5.13 

### Describe the Bug

Trying to use with vue 2.7 got this compatibility/dependency error.

`Error: @storybook/builder-vite requires @vitejs/plugin-vue to be installed when using @storybook/vue or @storybook/vue3.  Please install it and start storybook again.`

But vue 2.7 does not require `@vitejs/plugin-vue` because it uses `@vitejs/plugin-vue-2`
So you cannot use this builder if you are using vue 2.7

Thanks!

### Link to Minimal Reproducible Example

not necessary

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
You are running an older version of this package, please update @storybook/builder-vite to the latest version (0.2.5), which supports Vue 2.7.

**Comment by AlEsGoGit** [comment]
> You are running an older version of this package, please update @storybook/builder-vite to the latest version (0.2.5), which supports Vue 2.7.

I red this in the docs.
`Vite 3.0 or newer (for Vite v2 (2.5+), use @storybook/builder-vite@0.1.x)`
Thats why im  using the 0.1 version.

**Comment by IanVS** [comment]
In your issue you said you are using vite 3.2.0, which means you can use the new version of this package.  If you're on an old 2.x version of vite, and you want to use vue 2.7 and storybook builder-vite, you'll need to upgrade vite.

**Comment by AlEsGoGit** [comment]
My bad sorry, it works as expected with the latest version as you said.

**Comment by IanVS** [comment]
Great, glad it's working!  🙌
