### ISSUE TITLE
Pre-bundling dependencies

### ISSUE THREAD

**Issue by leyenda** [storybookjs/builder-vite#75]
Hello everyone, 

Is it normal that each time that I run storybook the cli keeps showing: "Pre-bundling dependencies (this will be run only when your dependencies or config have changed)".

It's like the cache from vite is not working or should I put something in the config.

Thank you in advance.

Here is my actual config: 

```js
async viteFinal(config, { configType }) {
    return {
      ...config,
      resolve: {
        alias: [
          {find: '@', replacement: path.resolve(__dirname, '../src')},
          {find: 'ag-grid', replacement: path.resolve(__dirname, '../node_modules/ag-grid-community/dist/styles/ag-grid.css')},
          {find: 'ag-theme-alpine', replacement: path.resolve(__dirname, '../node_modules/ag-grid-community/dist/styles/ag-theme-alpine.css')},
          {find: 'vue', replacement: 'vue/dist/vue.esm-bundler.js'}
        ]
      },
      cacheDir: path.resolve(__dirname, '../node_modules/.cache/vite'),
      optimizeDeps: {
        ...config.optimizeDeps,
        entries: [`${path.relative(config.root, path.resolve(__dirname, '../src'))}/**/*.stories.js`],
        include: [...config.optimizeDeps.include],
      },
    }
  }
```

**Comment by IanVS** [comment]
Do you still get the message if you add those dependencies that it pre-bundles into `optimizeDeps`?  And FWIW, `include: [...config.optimizeDeps.include],` is unnecessary, since you're already spreading it as part of `config.optimizeDeps` two lines above it.

**Comment by leyenda** [comment]
Thank you for your response Ian, Yes I was writting the dependencies there, for example:

```js
optimizeDeps: {
        ...config.optimizeDeps,
        entries: [`${path.relative(config.root, path.resolve(__dirname, '../src'))}/**/*.stories.js`],
        include: ['vue-i18n', 'vue3-tel-input', 'vee-validate', ...config.optimizeDeps.include],
      },
```

But the console keeps showing 
```
info @storybook/vue3 v6.4.0-alpha.18
info 
info => Loading presets
info => Using prebuilt manager
Pre-bundling dependencies:
  @storybook/addon-actions
  vue-i18n
  vue
  vue3-tel-input
  vee-validate
  (...and 76 more)
(this will be run only when your dependencies or config have changed)
```

Each time I run storybook.

**Comment by eirslett** [comment]
It happens to me as well. Not sure if it's a bug. It doesn't bother me a lot, since Vite starts almost instantly in every case, but I think it will use the pre-cached/optimized deps from last time you ran Storybook - it just logs the message anyways?

**Comment by thebuilder** [comment]
Also wondering what's up with this. Vite is fast to start, but going through all these bundles takes a full minute.

**Comment by eirslett** [comment]
> Also wondering what's up with this. Vite is fast to start, but going through all these bundles takes a full minute.

👁👄👁 
It takes 2-3 seconds here. Are you preoptimizing a lot of other dependencies as well?

**Comment by thebuilder** [comment]
Sorry, what I was seeing was it discovering new dependencies after that initial list, and it would keep finding new ones did about a minute. I think it's dependencies that's used in async modules, so they aren't added to the initial bundle. But it should still only so that on the first run, like Vite standalone. 

I added these dependencies manually into the optimzeDeps includes list, and now it's starting up in a couple of seconds again.

**Comment by gomorizsolt** [comment]
Same here... did anyone happen to resolve it? In my case, it's not a huge issue either because the dev server is up and running less than a couple of seconds, but still it shouldn't re-run the pre-bundling process unless if needed.

**Comment by zheeeng** [comment]
I took me about minutes

**Comment by siva-sundar** [comment]
Is there a way to resolve this ? Facing the same.

**Comment by IanVS** [comment]
@siva-sundar what issue are you seeing exactly?  Can you provide some details of what is happening, vs what you expect?

**Comment by extrem7** [comment]
It takes 40 second for me to display stories after `Storybook 6.4.20 for Vue3 started`

**Comment by IanVS** [comment]
@extrem7 have you tried enabling `features.storystoreV7`?  It can help initial load performance a lot.

**Comment by extrem7** [comment]
Yes, enabling storyStoreV7 increases start-up time to ~10s.

**Comment by IanVS** [comment]
@extrem7 it _increases_ start-up?  That's very odd!  Any chance this is a public repository I could take a look at?

**Comment by extrem7** [comment]
Sorry for my French) Time was totally reduced!

**Comment by zheeeng** [comment]
pre-bunding enhancement indeed saved the bootstrap time.

**Comment by IanVS** [comment]
Thanks for confirming, @zheeeng!  I'll close this out, but if anyone's still seeing long times, let me know and we can re-open and investigate.
