### ISSUE TITLE
Support CSF3 automatic titles

### ISSUE THREAD

**Issue by thebuilder** [storybookjs/builder-vite#77]
Storybook 6.4 introduces a new way to find stories, to support automatic title generation for CSF3. 
This currently breaks in the Vite builder, since it assumes the paths are always strings.

```js
module.exports = {
  stories: [
   { directory: '../src', files: '*.story.tsx', titlePrefix: 'foo' },
  ]
};
```

This throws an error: 
![image](https://user-images.githubusercontent.com/3764345/126774592-84ca85b0-992d-400c-93c4-5d9dad15dc29.png)

Caused by this line:
https://github.com/eirslett/storybook-builder-vite/blob/main/packages/storybook-builder-vite/codegen-iframe-script.js#L33

Stories can also be defined in a shorter string manner, but this will also break. The magic globbing logic should be applied to this one.

```js
module.exports = {
  stories: ['../src']
};
```

Results in:
![image](https://user-images.githubusercontent.com/3764345/126775187-94d7a6d1-1b55-4f5d-92e2-fd85103d96eb.png)

**Comment by IanVS** [comment]
This is being addressed in https://github.com/eirslett/storybook-builder-vite/pull/76.
